// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/types/common.proto

// @ts-nocheck
// oxlint-disable

/** Hashing functions supported by HTLC-related flows. */
export const HashingFunction = {
  HASHING_FUNCTION_KECCAK256: "HASHING_FUNCTION_KECCAK256",
  HASHING_FUNCTION_SHA256: "HASHING_FUNCTION_SHA256",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type HashingFunction = (typeof HashingFunction)[keyof typeof HashingFunction];

export namespace HashingFunction {
  export type HASHING_FUNCTION_KECCAK256 = typeof HashingFunction.HASHING_FUNCTION_KECCAK256;
  export type HASHING_FUNCTION_SHA256 = typeof HashingFunction.HASHING_FUNCTION_SHA256;
  export type UNRECOGNIZED = typeof HashingFunction.UNRECOGNIZED;
}

export function hashingFunctionFromJSON(object: any): HashingFunction {
  switch (object) {
    case 0:
    case "HASHING_FUNCTION_KECCAK256":
      return HashingFunction.HASHING_FUNCTION_KECCAK256;
    case 1:
    case "HASHING_FUNCTION_SHA256":
      return HashingFunction.HASHING_FUNCTION_SHA256;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HashingFunction.UNRECOGNIZED;
  }
}

export function hashingFunctionToJSON(object: HashingFunction): number {
  switch (object) {
    case HashingFunction.HASHING_FUNCTION_KECCAK256:
      return 0;
    case HashingFunction.HASHING_FUNCTION_SHA256:
      return 1;
    case HashingFunction.UNRECOGNIZED:
    default:
      return -1;
  }
}

/** High-level status of a trade, order, or swap lifecycle. */
export const TradeStatus = {
  /** TRADE_STATUS_IN_PROGRESS - The trade has been created and may still be settled successfully. */
  TRADE_STATUS_IN_PROGRESS: "TRADE_STATUS_IN_PROGRESS",
  /** TRADE_STATUS_FULLY_FILLED - The trade has been settled successfully in full. */
  TRADE_STATUS_FULLY_FILLED: "TRADE_STATUS_FULLY_FILLED",
  /**
   * TRADE_STATUS_PARTIALLY_FILLED - The trade has been settled successfully only for part of the requested
   * amount.
   */
  TRADE_STATUS_PARTIALLY_FILLED: "TRADE_STATUS_PARTIALLY_FILLED",
  /**
   * TRADE_STATUS_CANCELLED - The trade has been terminated by an explicit cancellation operation
   * (for example, by the trader cancelling the order).
   */
  TRADE_STATUS_CANCELLED: "TRADE_STATUS_CANCELLED",
  /**
   * TRADE_STATUS_FAILED - The trade could not be settled successfully because of a market,
   * protocol, routing, timeout, or other execution failure.
   */
  TRADE_STATUS_FAILED: "TRADE_STATUS_FAILED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type TradeStatus = (typeof TradeStatus)[keyof typeof TradeStatus];

export namespace TradeStatus {
  export type TRADE_STATUS_IN_PROGRESS = typeof TradeStatus.TRADE_STATUS_IN_PROGRESS;
  export type TRADE_STATUS_FULLY_FILLED = typeof TradeStatus.TRADE_STATUS_FULLY_FILLED;
  export type TRADE_STATUS_PARTIALLY_FILLED = typeof TradeStatus.TRADE_STATUS_PARTIALLY_FILLED;
  export type TRADE_STATUS_CANCELLED = typeof TradeStatus.TRADE_STATUS_CANCELLED;
  export type TRADE_STATUS_FAILED = typeof TradeStatus.TRADE_STATUS_FAILED;
  export type UNRECOGNIZED = typeof TradeStatus.UNRECOGNIZED;
}

export function tradeStatusFromJSON(object: any): TradeStatus {
  switch (object) {
    case 0:
    case "TRADE_STATUS_IN_PROGRESS":
      return TradeStatus.TRADE_STATUS_IN_PROGRESS;
    case 1:
    case "TRADE_STATUS_FULLY_FILLED":
      return TradeStatus.TRADE_STATUS_FULLY_FILLED;
    case 2:
    case "TRADE_STATUS_PARTIALLY_FILLED":
      return TradeStatus.TRADE_STATUS_PARTIALLY_FILLED;
    case 3:
    case "TRADE_STATUS_CANCELLED":
      return TradeStatus.TRADE_STATUS_CANCELLED;
    case 4:
    case "TRADE_STATUS_FAILED":
      return TradeStatus.TRADE_STATUS_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TradeStatus.UNRECOGNIZED;
  }
}

export function tradeStatusToJSON(object: TradeStatus): number {
  switch (object) {
    case TradeStatus.TRADE_STATUS_IN_PROGRESS:
      return 0;
    case TradeStatus.TRADE_STATUS_FULLY_FILLED:
      return 1;
    case TradeStatus.TRADE_STATUS_PARTIALLY_FILLED:
      return 2;
    case TradeStatus.TRADE_STATUS_CANCELLED:
      return 3;
    case TradeStatus.TRADE_STATUS_FAILED:
      return 4;
    case TradeStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

/**
 * The server periodically emits `KeepAlive` message to keep the connection
 * alive.
 */
export interface KeepAlive {}

function createBaseKeepAlive(): KeepAlive {
  return {};
}

export const KeepAlive: MessageFns<KeepAlive> = {
  fromJSON(_: any): KeepAlive {
    return {};
  },

  toJSON(_: KeepAlive): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<KeepAlive>, I>>(base?: I): KeepAlive {
    return KeepAlive.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeepAlive>, I>>(_: I): KeepAlive {
    const message = createBaseKeepAlive();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
