// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/types/htlc.proto

// @ts-nocheck
// oxlint-disable

import { AssetId } from "../../../common/v1/types/asset_id";
import { ChainAddress } from "../../../common/v1/types/chain_address";

/** Version 1 of the off-chain HTLC order-details structure. */
export interface HtlcOrderDetailsV1 {
  /** The ID of quote received from `QuoteRpc` */
  quoteId: string;
  outputAsset: AssetId;
  /**
   * The address on **Destination** blockchain that should receive the
   * **Output asset** after the secret is disclosed.
   */
  traderDstAddress: ChainAddress;
  /**
   * The address on **Destination** blockchain that must disclose the secret to
   * claim or redeem the **Output position** on the **Destination** blockchain.
   *
   * This address is distinct from `trader_dst_address`.
   * It should be omitted when using public disclosure of the secret.
   */
  traderDstDiscloseAddress?: ChainAddress | undefined;
  /**
   * Ordered list of secret hashes, one per HTLC execution attempt.
   *
   * The secrets are hashed with the function specified in
   * `OrderSettlementData.htlc_hashing_function` of the `Quote`.
   */
  secretHashes: Uint8Array[];
}

/** Versioned wrapper for off-chain HTLC order details. */
export interface VersionedHtlcOrderDetails {
  details: {
    $case: "version1";
    value: HtlcOrderDetailsV1;
  };
}

/** Requests protocol-side generation of HTLC secrets. */
export interface SecretModeGenerated {
  /**
   * Request the system to generate secrets automatically for the specified
   * number of executions. One secret is generated per execution/chunk.
   */
  maxExecutions: number;
}

/** Provides explicit HTLC secret hashes instead of generating them server-side. */
export interface SecretModeProvided {
  /**
   * Ordered list of secret hashes, one per HTLC execution attempt.
   *
   * The trader must use the hashing function specified in
   * `OrderSettlementData.htlc_hashing_function`.
   */
  hashes: Uint8Array[];
}

/**
 * Allows the trader to choose how secrets for a multi-chunk HTLC position are
 * defined.
 */
export interface HtlcSecrets {
  secretMode:
    //
    /**
     * Request the system to generate secrets automatically for the specified
     * number of executions.
     */
    | {
        $case: "generated";
        value: SecretModeGenerated;
      } //
    /**
     * Provide an explicit, ordered list of secret hashes (one per chunk).
     * Each hash must be a 32-byte value matching the on-chain chunk indexing.
     *
     * The trader must use the hashing function specified in
     * `OrderSettlementData.htlc_hashing_function`.
     */
    | {
        $case: "provided";
        value: SecretModeProvided;
      };
}

function createBaseHtlcOrderDetailsV1(): HtlcOrderDetailsV1 {
  return {
    quoteId: "",
    outputAsset: undefined,
    traderDstAddress: undefined,
    traderDstDiscloseAddress: undefined,
    secretHashes: [],
  };
}

export const HtlcOrderDetailsV1: MessageFns<HtlcOrderDetailsV1> = {
  fromJSON(object: any): HtlcOrderDetailsV1 {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      outputAsset: isSet(object.output_asset) ? AssetId.fromJSON(object.output_asset) : undefined,
      traderDstAddress: isSet(object.trader_dst_address)
        ? ChainAddress.fromJSON(object.trader_dst_address)
        : undefined,
      traderDstDiscloseAddress: isSet(object.trader_dst_disclose_address)
        ? ChainAddress.fromJSON(object.trader_dst_disclose_address)
        : undefined,
      secretHashes: globalThis.Array.isArray(object?.secret_hashes)
        ? object.secret_hashes.map((e: any) => bytesFromBase64(e))
        : [],
    };
  },

  toJSON(message: HtlcOrderDetailsV1): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.outputAsset !== undefined) {
      obj.output_asset = AssetId.toJSON(message.outputAsset);
    }
    if (message.traderDstAddress !== undefined) {
      obj.trader_dst_address = ChainAddress.toJSON(message.traderDstAddress);
    }
    if (message.traderDstDiscloseAddress !== undefined) {
      obj.trader_dst_disclose_address = ChainAddress.toJSON(message.traderDstDiscloseAddress);
    }
    if (message.secretHashes?.length) {
      obj.secret_hashes = message.secretHashes.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HtlcOrderDetailsV1>, I>>(base?: I): HtlcOrderDetailsV1 {
    return HtlcOrderDetailsV1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HtlcOrderDetailsV1>, I>>(object: I): HtlcOrderDetailsV1 {
    const message = createBaseHtlcOrderDetailsV1();
    message.quoteId = object.quoteId ?? "";
    message.outputAsset =
      object.outputAsset !== undefined && object.outputAsset !== null
        ? AssetId.fromPartial(object.outputAsset)
        : undefined;
    message.traderDstAddress =
      object.traderDstAddress !== undefined && object.traderDstAddress !== null
        ? ChainAddress.fromPartial(object.traderDstAddress)
        : undefined;
    message.traderDstDiscloseAddress =
      object.traderDstDiscloseAddress !== undefined && object.traderDstDiscloseAddress !== null
        ? ChainAddress.fromPartial(object.traderDstDiscloseAddress)
        : undefined;
    message.secretHashes = object.secretHashes?.map((e) => e) || [];
    return message;
  },
};

function createBaseVersionedHtlcOrderDetails(): VersionedHtlcOrderDetails {
  return { details: undefined };
}

export const VersionedHtlcOrderDetails: MessageFns<VersionedHtlcOrderDetails> = {
  fromJSON(object: any): VersionedHtlcOrderDetails {
    return {
      details: isSet(object.version1)
        ? { $case: "version1", value: HtlcOrderDetailsV1.fromJSON(object.version1) }
        : undefined,
    };
  },

  toJSON(message: VersionedHtlcOrderDetails): unknown {
    const obj: any = {};
    if (message.details?.$case === "version1") {
      obj.version1 = HtlcOrderDetailsV1.toJSON(message.details.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VersionedHtlcOrderDetails>, I>>(
    base?: I,
  ): VersionedHtlcOrderDetails {
    return VersionedHtlcOrderDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VersionedHtlcOrderDetails>, I>>(
    object: I,
  ): VersionedHtlcOrderDetails {
    const message = createBaseVersionedHtlcOrderDetails();
    switch (object.details?.$case) {
      case "version1": {
        if (object.details?.value !== undefined && object.details?.value !== null) {
          message.details = {
            $case: "version1",
            value: HtlcOrderDetailsV1.fromPartial(object.details.value),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseSecretModeGenerated(): SecretModeGenerated {
  return { maxExecutions: 0 };
}

export const SecretModeGenerated: MessageFns<SecretModeGenerated> = {
  fromJSON(object: any): SecretModeGenerated {
    return {
      maxExecutions: isSet(object.max_executions) ? globalThis.Number(object.max_executions) : 0,
    };
  },

  toJSON(message: SecretModeGenerated): unknown {
    const obj: any = {};
    if (message.maxExecutions !== undefined) {
      obj.max_executions = Math.round(message.maxExecutions);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SecretModeGenerated>, I>>(base?: I): SecretModeGenerated {
    return SecretModeGenerated.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SecretModeGenerated>, I>>(
    object: I,
  ): SecretModeGenerated {
    const message = createBaseSecretModeGenerated();
    message.maxExecutions = object.maxExecutions ?? 0;
    return message;
  },
};

function createBaseSecretModeProvided(): SecretModeProvided {
  return { hashes: [] };
}

export const SecretModeProvided: MessageFns<SecretModeProvided> = {
  fromJSON(object: any): SecretModeProvided {
    return {
      hashes: globalThis.Array.isArray(object?.hashes)
        ? object.hashes.map((e: any) => bytesFromBase64(e))
        : [],
    };
  },

  toJSON(message: SecretModeProvided): unknown {
    const obj: any = {};
    if (message.hashes?.length) {
      obj.hashes = message.hashes.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SecretModeProvided>, I>>(base?: I): SecretModeProvided {
    return SecretModeProvided.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SecretModeProvided>, I>>(object: I): SecretModeProvided {
    const message = createBaseSecretModeProvided();
    message.hashes = object.hashes?.map((e) => e) || [];
    return message;
  },
};

function createBaseHtlcSecrets(): HtlcSecrets {
  return { secretMode: undefined };
}

export const HtlcSecrets: MessageFns<HtlcSecrets> = {
  fromJSON(object: any): HtlcSecrets {
    return {
      secretMode: isSet(object.generated)
        ? { $case: "generated", value: SecretModeGenerated.fromJSON(object.generated) }
        : isSet(object.provided)
          ? { $case: "provided", value: SecretModeProvided.fromJSON(object.provided) }
          : undefined,
    };
  },

  toJSON(message: HtlcSecrets): unknown {
    const obj: any = {};
    if (message.secretMode?.$case === "generated") {
      obj.generated = SecretModeGenerated.toJSON(message.secretMode.value);
    } else if (message.secretMode?.$case === "provided") {
      obj.provided = SecretModeProvided.toJSON(message.secretMode.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HtlcSecrets>, I>>(base?: I): HtlcSecrets {
    return HtlcSecrets.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HtlcSecrets>, I>>(object: I): HtlcSecrets {
    const message = createBaseHtlcSecrets();
    switch (object.secretMode?.$case) {
      case "generated": {
        if (object.secretMode?.value !== undefined && object.secretMode?.value !== null) {
          message.secretMode = {
            $case: "generated",
            value: SecretModeGenerated.fromPartial(object.secretMode.value),
          };
        }
        break;
      }
      case "provided": {
        if (object.secretMode?.value !== undefined && object.secretMode?.value !== null) {
          message.secretMode = {
            $case: "provided",
            value: SecretModeProvided.fromPartial(object.secretMode.value),
          };
        }
        break;
      }
    }
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
