// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/types/order.proto

// @ts-nocheck
// oxlint-disable

import { ChainAddress } from "../../../common/v1/types/chain_address";
import { KeepAlive, TradeStatus, tradeStatusFromJSON, tradeStatusToJSON } from "./common";

export const ExecutionPhase = {
  /**
   * EXECUTION_PHASE_CREATED - The position has been created and is reserved for filling by the resolver
   * that created the reservation.
   *
   * During this phase, the resolver that created the reservation can proceed
   * with settlement.
   */
  EXECUTION_PHASE_CREATED: "EXECUTION_PHASE_CREATED",
  /**
   * EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION - (HTLC only) The creation transaction has reached on-chain finality and can
   * no longer be reverted. The resolver that created the reservation may
   * proceed with the successful completion flow of the execution.
   */
  EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION: "EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION",
  /**
   * EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION - (HTLC only) Public completion is allowed: the private completion window for
   * the resolver that created the reservation has ended, and any authorized
   * resolver may proceed with completion according to protocol rules.
   */
  EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION: "EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION",
  /**
   * EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK - The resolver that created the reservation may proceed with the private
   * rollback flow of the execution.
   */
  EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK: "EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK",
  /**
   * EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK - Public rollback is allowed. Any authorized resolver may proceed with
   * rollback according to protocol rules. Only the **Input position** enters
   * this phase.
   */
  EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK: "EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK",
  /**
   * EXECUTION_PHASE_COMPLETED - Final state: the execution completed successfully (funds unlocked as
   * intended).
   */
  EXECUTION_PHASE_COMPLETED: "EXECUTION_PHASE_COMPLETED",
  /**
   * EXECUTION_PHASE_ROLLED_BACK - Final state: the execution has been rolled back according to protocol
   * rules.
   */
  EXECUTION_PHASE_ROLLED_BACK: "EXECUTION_PHASE_ROLLED_BACK",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type ExecutionPhase = (typeof ExecutionPhase)[keyof typeof ExecutionPhase];

export namespace ExecutionPhase {
  export type EXECUTION_PHASE_CREATED = typeof ExecutionPhase.EXECUTION_PHASE_CREATED;
  export type EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION =
    typeof ExecutionPhase.EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION;
  export type EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION =
    typeof ExecutionPhase.EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION;
  export type EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK =
    typeof ExecutionPhase.EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK;
  export type EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK =
    typeof ExecutionPhase.EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK;
  export type EXECUTION_PHASE_COMPLETED = typeof ExecutionPhase.EXECUTION_PHASE_COMPLETED;
  export type EXECUTION_PHASE_ROLLED_BACK = typeof ExecutionPhase.EXECUTION_PHASE_ROLLED_BACK;
  export type UNRECOGNIZED = typeof ExecutionPhase.UNRECOGNIZED;
}

export function executionPhaseFromJSON(object: any): ExecutionPhase {
  switch (object) {
    case 0:
    case "EXECUTION_PHASE_CREATED":
      return ExecutionPhase.EXECUTION_PHASE_CREATED;
    case 1:
    case "EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION":
      return ExecutionPhase.EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION;
    case 2:
    case "EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION":
      return ExecutionPhase.EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION;
    case 3:
    case "EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK":
      return ExecutionPhase.EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK;
    case 4:
    case "EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK":
      return ExecutionPhase.EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK;
    case 10:
    case "EXECUTION_PHASE_COMPLETED":
      return ExecutionPhase.EXECUTION_PHASE_COMPLETED;
    case 11:
    case "EXECUTION_PHASE_ROLLED_BACK":
      return ExecutionPhase.EXECUTION_PHASE_ROLLED_BACK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExecutionPhase.UNRECOGNIZED;
  }
}

export function executionPhaseToJSON(object: ExecutionPhase): number {
  switch (object) {
    case ExecutionPhase.EXECUTION_PHASE_CREATED:
      return 0;
    case ExecutionPhase.EXECUTION_PHASE_READY_FOR_PRIVATE_COMPLETION:
      return 1;
    case ExecutionPhase.EXECUTION_PHASE_READY_FOR_PUBLIC_COMPLETION:
      return 2;
    case ExecutionPhase.EXECUTION_PHASE_READY_FOR_PRIVATE_ROLLBACK:
      return 3;
    case ExecutionPhase.EXECUTION_PHASE_READY_FOR_PUBLIC_ROLLBACK:
      return 4;
    case ExecutionPhase.EXECUTION_PHASE_COMPLETED:
      return 10;
    case ExecutionPhase.EXECUTION_PHASE_ROLLED_BACK:
      return 11;
    case ExecutionPhase.UNRECOGNIZED:
    default:
      return -1;
  }
}

export const OrderCancellationMode = {
  /** ORDER_CANCELLATION_MODE_UNAVAILABLE - The order cannot be cancelled by the trader in the current state. */
  ORDER_CANCELLATION_MODE_UNAVAILABLE: "ORDER_CANCELLATION_MODE_UNAVAILABLE",
  /** ORDER_CANCELLATION_MODE_OFFCHAIN - The order can be cancelled by an off-chain request. */
  ORDER_CANCELLATION_MODE_OFFCHAIN: "ORDER_CANCELLATION_MODE_OFFCHAIN",
  /**
   * ORDER_CANCELLATION_MODE_ONCHAIN - The order can be cancelled only by sending an on-chain cancellation
   * transaction.
   */
  ORDER_CANCELLATION_MODE_ONCHAIN: "ORDER_CANCELLATION_MODE_ONCHAIN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type OrderCancellationMode =
  (typeof OrderCancellationMode)[keyof typeof OrderCancellationMode];

export namespace OrderCancellationMode {
  export type ORDER_CANCELLATION_MODE_UNAVAILABLE =
    typeof OrderCancellationMode.ORDER_CANCELLATION_MODE_UNAVAILABLE;
  export type ORDER_CANCELLATION_MODE_OFFCHAIN =
    typeof OrderCancellationMode.ORDER_CANCELLATION_MODE_OFFCHAIN;
  export type ORDER_CANCELLATION_MODE_ONCHAIN =
    typeof OrderCancellationMode.ORDER_CANCELLATION_MODE_ONCHAIN;
  export type UNRECOGNIZED = typeof OrderCancellationMode.UNRECOGNIZED;
}

export function orderCancellationModeFromJSON(object: any): OrderCancellationMode {
  switch (object) {
    case 0:
    case "ORDER_CANCELLATION_MODE_UNAVAILABLE":
      return OrderCancellationMode.ORDER_CANCELLATION_MODE_UNAVAILABLE;
    case 1:
    case "ORDER_CANCELLATION_MODE_OFFCHAIN":
      return OrderCancellationMode.ORDER_CANCELLATION_MODE_OFFCHAIN;
    case 2:
    case "ORDER_CANCELLATION_MODE_ONCHAIN":
      return OrderCancellationMode.ORDER_CANCELLATION_MODE_ONCHAIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderCancellationMode.UNRECOGNIZED;
  }
}

export function orderCancellationModeToJSON(object: OrderCancellationMode): number {
  switch (object) {
    case OrderCancellationMode.ORDER_CANCELLATION_MODE_UNAVAILABLE:
      return 0;
    case OrderCancellationMode.ORDER_CANCELLATION_MODE_OFFCHAIN:
      return 1;
    case OrderCancellationMode.ORDER_CANCELLATION_MODE_ONCHAIN:
      return 2;
    case OrderCancellationMode.UNRECOGNIZED:
    default:
      return -1;
  }
}

/** Availability windows for completion and rollback of a position. */
export interface ExecutionPhaseTimestamps {
  /**
   * (HTLC only) Timestamp (UTC seconds) after which the resolver that created
   * the reservation may proceed with private completion of this position.
   */
  privateCompletionAvailableTimestamp?: number | undefined;
  /**
   * (HTLC only) Timestamp (UTC seconds) after which this position becomes
   * available for public completion.
   *
   * After this timestamp, any authorized resolver may proceed with completion
   * according to protocol rules.
   */
  publicCompletionAvailableTimestamp?: number | undefined;
  /**
   * Timestamp (UTC seconds) after which the resolver that created the
   * reservation may proceed with private rollback of this position.
   */
  privateRollbackAvailableTimestamp: number;
  /**
   * Timestamp (UTC seconds) after which any authorized resolver may proceed
   * with public rollback.
   *
   * This field is only defined for the **Input position**.
   */
  publicRollbackAvailableTimestamp?: number | undefined;
}

/** Progress and state of a single order execution or fill fragment. */
export interface Execution {
  /**
   * Index of execution for partial fills.
   *
   * This parameter contains 0 for single-fill trades.
   */
  index: number;
  /** Amount of **Input asset** reserved for this execution. */
  inputUnits: string;
  /** The net amount of **Output asset** the trader will receive after all fees. */
  outputUnits: string;
  /**
   * The total amount of **Output asset** the resolver should send, including
   * protocol and integrator fees.
   */
  resolverSendsUnits: string;
  /**
   * (HTLC-Only) The hash of the secret that locks the position.
   *
   * This parameter is omitted for intrachain swaps.
   */
  secretHash?: Uint8Array | undefined;
  /** ID of the resolver. */
  resolverId: string;
  /** Name of the resolver. */
  resolverName: string;
  /** Address of the **Input position** on **Source blockchain**. */
  inputPositionAddress: ChainAddress;
  /**
   * Current lifecycle phase of the **Input position** on **Source blockchain**.
   *
   * `ExecutionPhase` is tracked separately for the input position and, when a
   * flow has an output position, for the output position as well.
   */
  inputPositionPhase: ExecutionPhase;
  /**
   * Timestamps that define when completion or rollback becomes available for
   * the **Input position** on **Source blockchain**.
   */
  inputPositionPhaseTimestamps: ExecutionPhaseTimestamps;
  /**
   * Address of the resolver on **Source blockchain** that is authorized to
   * receive the **Input asset** upon successful completion of the execution.
   */
  srcResolverAddress: ChainAddress;
  /**
   * *[HTLC-Only]** Address of the **Output position** on **Destination
   * blockchain**
   *
   * This parameter is present for HTLC flows and omitted for intrachain flows.
   */
  outputPositionAddress?: ChainAddress | undefined;
  /**
   * *[HTLC-Only]** Current lifecycle phase of the **Output position** on
   * **Destination blockchain**.
   *
   * This is a separate phase track from `input_position_phase`.
   * This parameter is present for HTLC flows and omitted for intrachain flows.
   */
  outputPositionPhase?: ExecutionPhase | undefined;
  /**
   * *[HTLC-Only]** Timestamps that define when completion or rollback becomes
   * available for the
   * **Output position** on **Destination blockchain**.
   *
   * This parameter is present for HTLC flows and omitted for intrachain flows.
   */
  outputPositionPhaseTimestamps?: ExecutionPhaseTimestamps | undefined;
}

/** Current aggregated state of an order together with its executions. */
export interface Order {
  /** Status of the trade */
  status: TradeStatus;
  /**
   * Address of the protocol contract that executes the order.
   *
   * * For EVM: Address of limit order protocol contract
   * * For TON: Address of escrow contract
   */
  protocolContractAddress: ChainAddress;
  /**
   * The amount of **Input asset** of trader's position that remains to be
   * settled.
   *
   * This amount includes both tokens residing on trader's wallet and tokens
   * moved to escrow contract.
   */
  remainingInputUnits: string;
  /**
   * The amount of **Input asset** of trader's position that has been moved from
   * trader's wallet to escrow contract.
   */
  escrowedInputUnits: string;
  /** Cancellation mode currently available to the trader for this **Order**. */
  cancellationMode: OrderCancellationMode;
  /** List of executions that attempt to fill the order */
  executions: Execution[];
  /**
   * Estimated timestamp of settling.
   *
   * Empty if unknown (for example, for limit orders).
   */
  estimatedFinishTimestamp?: number | undefined;
}

export interface OrderStatusEvent {
  event:
    | {
        $case: "order";
        value: Order;
      } //
    /** The service message to keep connection alive */
    | {
        $case: "keepAlive";
        value: KeepAlive;
      };
}

export interface SignedOrderEvmV1 {
  /**
   * The body of the order in EVM ABI encoding.
   *
   * This payload is produced by the trader's wallet from TypedData returned by
   * `EvmRpc.BuildOrderPayload`, for example via `eth_signTypedData`.
   */
  encodedOrder: Uint8Array;
  /** Blockchain-specific signature of the order */
  signature: Uint8Array;
  /**
   * Encoded extension data of the order.
   *
   * This field must be copied as is from
   * `EvmOrderPayloadResponse.order_extension`.
   */
  orderExtension: Uint8Array;
}

/** Versioned wrapper for blockchain-specific signed orders. */
export interface SignedOrder {
  order: {
    $case: "evmV1";
    value: SignedOrderEvmV1;
  };
}

/** EVM-specific signed cancellation payload for a previously signed order. */
export interface SignedOrderCancellationEvmV1 {
  /**
   * The body of the cancellation in EVM ABI encoding.
   *
   * This payload is produced by the trader's wallet from TypedData returned by
   * `EvmRpc.BuildOrderCancellation`, for example via `eth_signTypedData`.
   */
  encodedCancellation: Uint8Array;
  /**
   * Blockchain-specific signature of the cancellation.
   *
   * The signature must be produced by the same wallet that signed the
   * corresponding **Signed Order**.
   */
  signature: Uint8Array;
}

/** Versioned wrapper for blockchain-specific signed order cancellations. */
export interface SignedOrderCancellation {
  cancellation: {
    $case: "evmV1";
    value: SignedOrderCancellationEvmV1;
  };
}

function createBaseExecutionPhaseTimestamps(): ExecutionPhaseTimestamps {
  return {
    privateCompletionAvailableTimestamp: undefined,
    publicCompletionAvailableTimestamp: undefined,
    privateRollbackAvailableTimestamp: 0,
    publicRollbackAvailableTimestamp: undefined,
  };
}

export const ExecutionPhaseTimestamps: MessageFns<ExecutionPhaseTimestamps> = {
  fromJSON(object: any): ExecutionPhaseTimestamps {
    return {
      privateCompletionAvailableTimestamp: isSet(object.private_completion_available_timestamp)
        ? globalThis.Number(object.private_completion_available_timestamp)
        : undefined,
      publicCompletionAvailableTimestamp: isSet(object.public_completion_available_timestamp)
        ? globalThis.Number(object.public_completion_available_timestamp)
        : undefined,
      privateRollbackAvailableTimestamp: isSet(object.private_rollback_available_timestamp)
        ? globalThis.Number(object.private_rollback_available_timestamp)
        : 0,
      publicRollbackAvailableTimestamp: isSet(object.public_rollback_available_timestamp)
        ? globalThis.Number(object.public_rollback_available_timestamp)
        : undefined,
    };
  },

  toJSON(message: ExecutionPhaseTimestamps): unknown {
    const obj: any = {};
    if (message.privateCompletionAvailableTimestamp !== undefined) {
      obj.private_completion_available_timestamp = Math.round(
        message.privateCompletionAvailableTimestamp,
      );
    }
    if (message.publicCompletionAvailableTimestamp !== undefined) {
      obj.public_completion_available_timestamp = Math.round(
        message.publicCompletionAvailableTimestamp,
      );
    }
    if (message.privateRollbackAvailableTimestamp !== undefined) {
      obj.private_rollback_available_timestamp = Math.round(
        message.privateRollbackAvailableTimestamp,
      );
    }
    if (message.publicRollbackAvailableTimestamp !== undefined) {
      obj.public_rollback_available_timestamp = Math.round(
        message.publicRollbackAvailableTimestamp,
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecutionPhaseTimestamps>, I>>(
    base?: I,
  ): ExecutionPhaseTimestamps {
    return ExecutionPhaseTimestamps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecutionPhaseTimestamps>, I>>(
    object: I,
  ): ExecutionPhaseTimestamps {
    const message = createBaseExecutionPhaseTimestamps();
    message.privateCompletionAvailableTimestamp =
      object.privateCompletionAvailableTimestamp ?? undefined;
    message.publicCompletionAvailableTimestamp =
      object.publicCompletionAvailableTimestamp ?? undefined;
    message.privateRollbackAvailableTimestamp = object.privateRollbackAvailableTimestamp ?? 0;
    message.publicRollbackAvailableTimestamp = object.publicRollbackAvailableTimestamp ?? undefined;
    return message;
  },
};

function createBaseExecution(): Execution {
  return {
    index: 0,
    inputUnits: "",
    outputUnits: "",
    resolverSendsUnits: "",
    secretHash: undefined,
    resolverId: "",
    resolverName: "",
    inputPositionAddress: undefined,
    inputPositionPhase: ExecutionPhase.EXECUTION_PHASE_CREATED,
    inputPositionPhaseTimestamps: undefined,
    srcResolverAddress: undefined,
    outputPositionAddress: undefined,
    outputPositionPhase: undefined,
    outputPositionPhaseTimestamps: undefined,
  };
}

export const Execution: MessageFns<Execution> = {
  fromJSON(object: any): Execution {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      inputUnits: isSet(object.input_units) ? globalThis.String(object.input_units) : "",
      outputUnits: isSet(object.output_units) ? globalThis.String(object.output_units) : "",
      resolverSendsUnits: isSet(object.resolver_sends_units)
        ? globalThis.String(object.resolver_sends_units)
        : "",
      secretHash: isSet(object.secret_hash) ? bytesFromBase64(object.secret_hash) : undefined,
      resolverId: isSet(object.resolver_id) ? globalThis.String(object.resolver_id) : "",
      resolverName: isSet(object.resolver_name) ? globalThis.String(object.resolver_name) : "",
      inputPositionAddress: isSet(object.input_position_address)
        ? ChainAddress.fromJSON(object.input_position_address)
        : undefined,
      inputPositionPhase: isSet(object.input_position_phase)
        ? executionPhaseFromJSON(object.input_position_phase)
        : ExecutionPhase.EXECUTION_PHASE_CREATED,
      inputPositionPhaseTimestamps: isSet(object.input_position_phase_timestamps)
        ? ExecutionPhaseTimestamps.fromJSON(object.input_position_phase_timestamps)
        : undefined,
      srcResolverAddress: isSet(object.src_resolver_address)
        ? ChainAddress.fromJSON(object.src_resolver_address)
        : undefined,
      outputPositionAddress: isSet(object.output_position_address)
        ? ChainAddress.fromJSON(object.output_position_address)
        : undefined,
      outputPositionPhase: isSet(object.output_position_phase)
        ? executionPhaseFromJSON(object.output_position_phase)
        : undefined,
      outputPositionPhaseTimestamps: isSet(object.output_position_phase_timestamps)
        ? ExecutionPhaseTimestamps.fromJSON(object.output_position_phase_timestamps)
        : undefined,
    };
  },

  toJSON(message: Execution): unknown {
    const obj: any = {};
    if (message.index !== undefined) {
      obj.index = Math.round(message.index);
    }
    if (message.inputUnits !== undefined) {
      obj.input_units = message.inputUnits;
    }
    if (message.outputUnits !== undefined) {
      obj.output_units = message.outputUnits;
    }
    if (message.resolverSendsUnits !== undefined) {
      obj.resolver_sends_units = message.resolverSendsUnits;
    }
    if (message.secretHash !== undefined) {
      obj.secret_hash = base64FromBytes(message.secretHash);
    }
    if (message.resolverId !== undefined) {
      obj.resolver_id = message.resolverId;
    }
    if (message.resolverName !== undefined) {
      obj.resolver_name = message.resolverName;
    }
    if (message.inputPositionAddress !== undefined) {
      obj.input_position_address = ChainAddress.toJSON(message.inputPositionAddress);
    }
    if (message.inputPositionPhase !== undefined) {
      obj.input_position_phase = executionPhaseToJSON(message.inputPositionPhase);
    }
    if (message.inputPositionPhaseTimestamps !== undefined) {
      obj.input_position_phase_timestamps = ExecutionPhaseTimestamps.toJSON(
        message.inputPositionPhaseTimestamps,
      );
    }
    if (message.srcResolverAddress !== undefined) {
      obj.src_resolver_address = ChainAddress.toJSON(message.srcResolverAddress);
    }
    if (message.outputPositionAddress !== undefined) {
      obj.output_position_address = ChainAddress.toJSON(message.outputPositionAddress);
    }
    if (message.outputPositionPhase !== undefined) {
      obj.output_position_phase = executionPhaseToJSON(message.outputPositionPhase);
    }
    if (message.outputPositionPhaseTimestamps !== undefined) {
      obj.output_position_phase_timestamps = ExecutionPhaseTimestamps.toJSON(
        message.outputPositionPhaseTimestamps,
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Execution>, I>>(base?: I): Execution {
    return Execution.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Execution>, I>>(object: I): Execution {
    const message = createBaseExecution();
    message.index = object.index ?? 0;
    message.inputUnits = object.inputUnits ?? "";
    message.outputUnits = object.outputUnits ?? "";
    message.resolverSendsUnits = object.resolverSendsUnits ?? "";
    message.secretHash = object.secretHash ?? undefined;
    message.resolverId = object.resolverId ?? "";
    message.resolverName = object.resolverName ?? "";
    message.inputPositionAddress =
      object.inputPositionAddress !== undefined && object.inputPositionAddress !== null
        ? ChainAddress.fromPartial(object.inputPositionAddress)
        : undefined;
    message.inputPositionPhase =
      object.inputPositionPhase ?? ExecutionPhase.EXECUTION_PHASE_CREATED;
    message.inputPositionPhaseTimestamps =
      object.inputPositionPhaseTimestamps !== undefined &&
      object.inputPositionPhaseTimestamps !== null
        ? ExecutionPhaseTimestamps.fromPartial(object.inputPositionPhaseTimestamps)
        : undefined;
    message.srcResolverAddress =
      object.srcResolverAddress !== undefined && object.srcResolverAddress !== null
        ? ChainAddress.fromPartial(object.srcResolverAddress)
        : undefined;
    message.outputPositionAddress =
      object.outputPositionAddress !== undefined && object.outputPositionAddress !== null
        ? ChainAddress.fromPartial(object.outputPositionAddress)
        : undefined;
    message.outputPositionPhase = object.outputPositionPhase ?? undefined;
    message.outputPositionPhaseTimestamps =
      object.outputPositionPhaseTimestamps !== undefined &&
      object.outputPositionPhaseTimestamps !== null
        ? ExecutionPhaseTimestamps.fromPartial(object.outputPositionPhaseTimestamps)
        : undefined;
    return message;
  },
};

function createBaseOrder(): Order {
  return {
    status: TradeStatus.TRADE_STATUS_IN_PROGRESS,
    protocolContractAddress: undefined,
    remainingInputUnits: "",
    escrowedInputUnits: "",
    cancellationMode: OrderCancellationMode.ORDER_CANCELLATION_MODE_UNAVAILABLE,
    executions: [],
    estimatedFinishTimestamp: undefined,
  };
}

export const Order: MessageFns<Order> = {
  fromJSON(object: any): Order {
    return {
      status: isSet(object.status)
        ? tradeStatusFromJSON(object.status)
        : TradeStatus.TRADE_STATUS_IN_PROGRESS,
      protocolContractAddress: isSet(object.protocol_contract_address)
        ? ChainAddress.fromJSON(object.protocol_contract_address)
        : undefined,
      remainingInputUnits: isSet(object.remaining_input_units)
        ? globalThis.String(object.remaining_input_units)
        : "",
      escrowedInputUnits: isSet(object.escrowed_input_units)
        ? globalThis.String(object.escrowed_input_units)
        : "",
      cancellationMode: isSet(object.cancellation_mode)
        ? orderCancellationModeFromJSON(object.cancellation_mode)
        : OrderCancellationMode.ORDER_CANCELLATION_MODE_UNAVAILABLE,
      executions: globalThis.Array.isArray(object?.executions)
        ? object.executions.map((e: any) => Execution.fromJSON(e))
        : [],
      estimatedFinishTimestamp: isSet(object.estimated_finish_timestamp)
        ? globalThis.Number(object.estimated_finish_timestamp)
        : undefined,
    };
  },

  toJSON(message: Order): unknown {
    const obj: any = {};
    if (message.status !== undefined) {
      obj.status = tradeStatusToJSON(message.status);
    }
    if (message.protocolContractAddress !== undefined) {
      obj.protocol_contract_address = ChainAddress.toJSON(message.protocolContractAddress);
    }
    if (message.remainingInputUnits !== undefined) {
      obj.remaining_input_units = message.remainingInputUnits;
    }
    if (message.escrowedInputUnits !== undefined) {
      obj.escrowed_input_units = message.escrowedInputUnits;
    }
    if (message.cancellationMode !== undefined) {
      obj.cancellation_mode = orderCancellationModeToJSON(message.cancellationMode);
    }
    if (message.executions?.length) {
      obj.executions = message.executions.map((e) => Execution.toJSON(e));
    }
    if (message.estimatedFinishTimestamp !== undefined) {
      obj.estimated_finish_timestamp = Math.round(message.estimatedFinishTimestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Order>, I>>(base?: I): Order {
    return Order.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Order>, I>>(object: I): Order {
    const message = createBaseOrder();
    message.status = object.status ?? TradeStatus.TRADE_STATUS_IN_PROGRESS;
    message.protocolContractAddress =
      object.protocolContractAddress !== undefined && object.protocolContractAddress !== null
        ? ChainAddress.fromPartial(object.protocolContractAddress)
        : undefined;
    message.remainingInputUnits = object.remainingInputUnits ?? "";
    message.escrowedInputUnits = object.escrowedInputUnits ?? "";
    message.cancellationMode =
      object.cancellationMode ?? OrderCancellationMode.ORDER_CANCELLATION_MODE_UNAVAILABLE;
    message.executions = object.executions?.map((e) => Execution.fromPartial(e)) || [];
    message.estimatedFinishTimestamp = object.estimatedFinishTimestamp ?? undefined;
    return message;
  },
};

function createBaseOrderStatusEvent(): OrderStatusEvent {
  return { event: undefined };
}

export const OrderStatusEvent: MessageFns<OrderStatusEvent> = {
  fromJSON(object: any): OrderStatusEvent {
    return {
      event: isSet(object.order)
        ? { $case: "order", value: Order.fromJSON(object.order) }
        : isSet(object.keep_alive)
          ? { $case: "keepAlive", value: KeepAlive.fromJSON(object.keep_alive) }
          : undefined,
    };
  },

  toJSON(message: OrderStatusEvent): unknown {
    const obj: any = {};
    if (message.event?.$case === "order") {
      obj.order = Order.toJSON(message.event.value);
    } else if (message.event?.$case === "keepAlive") {
      obj.keep_alive = KeepAlive.toJSON(message.event.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderStatusEvent>, I>>(base?: I): OrderStatusEvent {
    return OrderStatusEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderStatusEvent>, I>>(object: I): OrderStatusEvent {
    const message = createBaseOrderStatusEvent();
    switch (object.event?.$case) {
      case "order": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = { $case: "order", value: Order.fromPartial(object.event.value) };
        }
        break;
      }
      case "keepAlive": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = { $case: "keepAlive", value: KeepAlive.fromPartial(object.event.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseSignedOrderEvmV1(): SignedOrderEvmV1 {
  return {
    encodedOrder: new Uint8Array(0),
    signature: new Uint8Array(0),
    orderExtension: new Uint8Array(0),
  };
}

export const SignedOrderEvmV1: MessageFns<SignedOrderEvmV1> = {
  fromJSON(object: any): SignedOrderEvmV1 {
    return {
      encodedOrder: isSet(object.encoded_order)
        ? bytesFromBase64(object.encoded_order)
        : new Uint8Array(0),
      signature: isSet(object.signature) ? bytesFromBase64(object.signature) : new Uint8Array(0),
      orderExtension: isSet(object.order_extension)
        ? bytesFromBase64(object.order_extension)
        : new Uint8Array(0),
    };
  },

  toJSON(message: SignedOrderEvmV1): unknown {
    const obj: any = {};
    if (message.encodedOrder !== undefined) {
      obj.encoded_order = base64FromBytes(message.encodedOrder);
    }
    if (message.signature !== undefined) {
      obj.signature = base64FromBytes(message.signature);
    }
    if (message.orderExtension !== undefined) {
      obj.order_extension = base64FromBytes(message.orderExtension);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignedOrderEvmV1>, I>>(base?: I): SignedOrderEvmV1 {
    return SignedOrderEvmV1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedOrderEvmV1>, I>>(object: I): SignedOrderEvmV1 {
    const message = createBaseSignedOrderEvmV1();
    message.encodedOrder = object.encodedOrder ?? new Uint8Array(0);
    message.signature = object.signature ?? new Uint8Array(0);
    message.orderExtension = object.orderExtension ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSignedOrder(): SignedOrder {
  return { order: undefined };
}

export const SignedOrder: MessageFns<SignedOrder> = {
  fromJSON(object: any): SignedOrder {
    return {
      order: isSet(object.evm_v1)
        ? { $case: "evmV1", value: SignedOrderEvmV1.fromJSON(object.evm_v1) }
        : undefined,
    };
  },

  toJSON(message: SignedOrder): unknown {
    const obj: any = {};
    if (message.order?.$case === "evmV1") {
      obj.evm_v1 = SignedOrderEvmV1.toJSON(message.order.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignedOrder>, I>>(base?: I): SignedOrder {
    return SignedOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedOrder>, I>>(object: I): SignedOrder {
    const message = createBaseSignedOrder();
    switch (object.order?.$case) {
      case "evmV1": {
        if (object.order?.value !== undefined && object.order?.value !== null) {
          message.order = {
            $case: "evmV1",
            value: SignedOrderEvmV1.fromPartial(object.order.value),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseSignedOrderCancellationEvmV1(): SignedOrderCancellationEvmV1 {
  return { encodedCancellation: new Uint8Array(0), signature: new Uint8Array(0) };
}

export const SignedOrderCancellationEvmV1: MessageFns<SignedOrderCancellationEvmV1> = {
  fromJSON(object: any): SignedOrderCancellationEvmV1 {
    return {
      encodedCancellation: isSet(object.encoded_cancellation)
        ? bytesFromBase64(object.encoded_cancellation)
        : new Uint8Array(0),
      signature: isSet(object.signature) ? bytesFromBase64(object.signature) : new Uint8Array(0),
    };
  },

  toJSON(message: SignedOrderCancellationEvmV1): unknown {
    const obj: any = {};
    if (message.encodedCancellation !== undefined) {
      obj.encoded_cancellation = base64FromBytes(message.encodedCancellation);
    }
    if (message.signature !== undefined) {
      obj.signature = base64FromBytes(message.signature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignedOrderCancellationEvmV1>, I>>(
    base?: I,
  ): SignedOrderCancellationEvmV1 {
    return SignedOrderCancellationEvmV1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedOrderCancellationEvmV1>, I>>(
    object: I,
  ): SignedOrderCancellationEvmV1 {
    const message = createBaseSignedOrderCancellationEvmV1();
    message.encodedCancellation = object.encodedCancellation ?? new Uint8Array(0);
    message.signature = object.signature ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSignedOrderCancellation(): SignedOrderCancellation {
  return { cancellation: undefined };
}

export const SignedOrderCancellation: MessageFns<SignedOrderCancellation> = {
  fromJSON(object: any): SignedOrderCancellation {
    return {
      cancellation: isSet(object.evm_v1)
        ? { $case: "evmV1", value: SignedOrderCancellationEvmV1.fromJSON(object.evm_v1) }
        : undefined,
    };
  },

  toJSON(message: SignedOrderCancellation): unknown {
    const obj: any = {};
    if (message.cancellation?.$case === "evmV1") {
      obj.evm_v1 = SignedOrderCancellationEvmV1.toJSON(message.cancellation.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignedOrderCancellation>, I>>(
    base?: I,
  ): SignedOrderCancellation {
    return SignedOrderCancellation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedOrderCancellation>, I>>(
    object: I,
  ): SignedOrderCancellation {
    const message = createBaseSignedOrderCancellation();
    switch (object.cancellation?.$case) {
      case "evmV1": {
        if (object.cancellation?.value !== undefined && object.cancellation?.value !== null) {
          message.cancellation = {
            $case: "evmV1",
            value: SignedOrderCancellationEvmV1.fromPartial(object.cancellation.value),
          };
        }
        break;
      }
    }
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
