// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/types/quote.proto

// @ts-nocheck
// oxlint-disable

import { AssetId } from "../../../common/v1/types/asset_id";
import { ChainAddress } from "../../../common/v1/types/chain_address";
import { HashingFunction, hashingFunctionFromJSON, hashingFunctionToJSON } from "./common";
import { SwapRoute } from "./swap";

/**
 * *UNSTABLE:** This is unstable API, it's subject to backward-incompatible
 * changes.
 */
export const GaslessSettlement = {
  /** GASLESS_SETTLEMENT_PROHIBITED - Gasless settlement either unsupported or prohibited by trader. */
  GASLESS_SETTLEMENT_PROHIBITED: "GASLESS_SETTLEMENT_PROHIBITED",
  /** GASLESS_SETTLEMENT_POSSIBLE - Gasless possible. */
  GASLESS_SETTLEMENT_POSSIBLE: "GASLESS_SETTLEMENT_POSSIBLE",
  /** GASLESS_SETTLEMENT_REQUIRED - Gasless settlement required. */
  GASLESS_SETTLEMENT_REQUIRED: "GASLESS_SETTLEMENT_REQUIRED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type GaslessSettlement = (typeof GaslessSettlement)[keyof typeof GaslessSettlement];

export namespace GaslessSettlement {
  export type GASLESS_SETTLEMENT_PROHIBITED =
    typeof GaslessSettlement.GASLESS_SETTLEMENT_PROHIBITED;
  export type GASLESS_SETTLEMENT_POSSIBLE = typeof GaslessSettlement.GASLESS_SETTLEMENT_POSSIBLE;
  export type GASLESS_SETTLEMENT_REQUIRED = typeof GaslessSettlement.GASLESS_SETTLEMENT_REQUIRED;
  export type UNRECOGNIZED = typeof GaslessSettlement.UNRECOGNIZED;
}

export function gaslessSettlementFromJSON(object: any): GaslessSettlement {
  switch (object) {
    case 0:
    case "GASLESS_SETTLEMENT_PROHIBITED":
      return GaslessSettlement.GASLESS_SETTLEMENT_PROHIBITED;
    case 1:
    case "GASLESS_SETTLEMENT_POSSIBLE":
      return GaslessSettlement.GASLESS_SETTLEMENT_POSSIBLE;
    case 2:
    case "GASLESS_SETTLEMENT_REQUIRED":
      return GaslessSettlement.GASLESS_SETTLEMENT_REQUIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GaslessSettlement.UNRECOGNIZED;
  }
}

export function gaslessSettlementToJSON(object: GaslessSettlement): number {
  switch (object) {
    case GaslessSettlement.GASLESS_SETTLEMENT_PROHIBITED:
      return 0;
    case GaslessSettlement.GASLESS_SETTLEMENT_POSSIBLE:
      return 1;
    case GaslessSettlement.GASLESS_SETTLEMENT_REQUIRED:
      return 2;
    case GaslessSettlement.UNRECOGNIZED:
    default:
      return -1;
  }
}

/**
 * Additional parameters of RFQ specific to the **Swap settlement**.
 *
 * Some parameters might be valid only in a subset of settlement methods on a
 * subset of supported blockchains. These parameters might be omitted if
 * corresponding settlement methods won't be used.
 */
export interface SwapSettlementParams {
  /** Max price slippage in percentage in points (1/1,000,000 or 0.0001%) */
  maxPriceSlippagePips?: number | undefined;
  /**
   * Max number of outgoing messages supported by the wallet.
   *
   * For TON blockchain defaults to 4 if omitted.
   */
  maxRoutes?: number | undefined;
  /**
   * Indicates whether a flexible integrator fee can be applied for the quote.
   *
   * Allows inclusion of protocols that have limited support for integrator
   * fees.
   */
  flexibleIntegratorFee?: boolean | undefined;
  /**
   * Indicates whether risky routes can be used for settling the quote.
   *
   * Using these routes increase the chance of spending gas tokens with failed
   * swap attempts.
   */
  allowRiskyRoutes?: boolean | undefined;
}

/** Additional parameters of RFQ specific to the **Order settlement**. */
export interface OrderSettlementParams {}

/** Additional parameters of request specific to settlement methods. */
export interface SettlementParams {
  params:
    //
    /** Enables swap-settlement-specific preferences for this RFQ. */
    | {
        $case: "swap";
        value: SwapSettlementParams;
      } //
    /** Enables order-settlement-specific preferences for this RFQ. */
    | {
        $case: "order";
        value: OrderSettlementParams;
      };
}

/** Additional data of the quote specific to swap settlement. */
export interface SwapSettlementData {
  routes: SwapRoute[];
  minOutputAmount: string;
  recommendedMinOutputAmount: string;
  /** in percentage in points (1/1,000,000 or 0.0001%) */
  recommendedSlippagePips: number;
}

/** Additional data of the quote specific to the **Order settlement**. */
export interface OrderSettlementData {
  /**
   * Address of the protocol contract on **Source** blockchain that enforces the
   * swap.
   */
  srcProtocolContractAddress: ChainAddress;
  /**
   * Address of the wrapper contract for native token (pTON, wETH, etc.) on
   * **Source blockchain** that must be used to settle the trade.
   *
   * **Note:** some blockchains support multiple wrappers with different ABI.
   * The mechanics of working with the wrapper should be selected based on its
   * implementation.
   *
   * This parameter is omitted if **Input asset** is not native on corresponding
   * blockchain.
   */
  srcWrappedNativeTokenAddress?: ChainAddress | undefined;
  /**
   * Address of the resolver's wallet on the **Source blockchain** for which the
   * position is initially reserved (exclusive fill during the reservation
   * period).
   *
   * If omitted, the position is available for all authorized resolvers since
   * the creation.
   */
  srcInitialResolverAddress?: ChainAddress | undefined;
  /**
   * (HTLC-only) Asset used as the security deposit for HTLC settlement on
   * **Source blockchain**.
   *
   * This parameter is omitted for intrachain trades.
   */
  srcHtlcSecurityDepositAsset?: AssetId | undefined;
  /**
   * (HTLC-only) Amount of the security deposit on **Source blockchain** (in
   * units of `src_htlc_security_deposit_asset`).
   *
   * This parameter is omitted for intrachain trades.
   */
  srcHtlcSecurityDepositUnits?: string | undefined;
  /**
   * (HTLC-only) Hashing function used to compute secret hashes for HTLC chunks.
   *
   * This parameter is omitted for intrachain trades.
   */
  htlcHashingFunction?: HashingFunction | undefined;
  /**
   * (HTLC-only) Address of the protocol contract on **Destination blockchain**
   * that enforces the swap.
   *
   * This parameter is omitted for intrachain trades.
   */
  dstProtocolContractAddress?: ChainAddress | undefined;
  /**
   * The amount of **Output asset** that the resolver must use to fill the
   * order, including all fees.
   */
  resolverSendsUnits: string;
  /**
   * Address of the wrapper contract for native token (pTON, wETH, etc.) that
   * must be used to settle the trade.
   *
   * **Note:** some blockchains support multiple wrappers with different ABI.
   * The mechanics of working with the wrapper should be selected based on its
   * implementation.
   *
   * This parameter is omitted if **Output asset** is not native on
   * corresponding blockchain.
   */
  dstWrappedNativeTokenAddress?: ChainAddress | undefined;
  /**
   * (HTLC-only) Asset used as the security deposit for HTLC settlement on
   * **Destination blockchain**.
   *
   * This parameter is omitted for intrachain trades.
   */
  dstSecurityDepositAsset?: AssetId | undefined;
  /**
   * (HTLC-only) Amount of the security deposit on **Destination blockchain**
   * (in units of `dst_security_deposit_asset`).
   *
   * This parameter is omitted for intrachain trades.
   */
  dstSecurityDepositUnits?: string | undefined;
  /**
   * Max timestamp (UTC seconds) of start of the trade.
   *
   * The start of the trade is defined either as the timestamp of the reception
   * of **Input asset** by the protocol smart contract or the timestamp of
   * signing the order.
   *
   * The resolver may still settle the trades started after this deadline has
   * passed at own discretion.
   */
  tradeStartDeadline: number;
  /**
   * Maximum duration since the trader creates the position before the resolver
   * must reserve the position by making the security deposit.
   *
   * At the end of this period trader's position becomes available for manual
   * withdrawal and Dutch auction starts if specified by escrow condition.
   */
  exclusivityTimeout: number;
  /**
   * Integrator fee in percentage points (1/1,000,000 or 0.0001%).
   *
   * This field is copied from `QuoteRequest`.
   */
  integratorFeePips: number;
  /**
   * Protocol fee for the corresponding settlement method in percentage points
   * (1/1,000,000 or 0.0001%). The protocol fee is always collected in
   * **Output asset**.
   *
   * This field is copied from `ProtocolParams` of `QuoteRequestedEvent`.
   */
  protocolFeePips: number;
  /**
   * Address of the wallet on **Destination blockchain** that will receive the
   * protocol fees.
   *
   * If specified, this address must be used when building the destination-side
   * transaction.
   */
  protocolFeeRecipientAddress?: ChainAddress | undefined;
}

/** A request for quote (RFQ) sent by the trader */
export interface QuoteRequest {
  /** Blockchain-specific address of **Input asset**. */
  inputAsset: AssetId;
  /** Blockchain-specific address of **Output asset**. */
  outputAsset: AssetId;
  /**
   * Either the amount of **Input asset** or **Output asset**.
   *
   * `input_units` means the trader fixes how much input asset they are willing
   * to spend. `output_units` means the trader fixes the net amount of output
   * asset they want to receive after all fees.
   */
  amount:
    //
    /**
     * The amount of **Input asset** the trader wants to send, including all
     * fees.
     */
    | {
        $case: "inputUnits";
        value: string;
      } //
    /**
     * The amount of **Output asset** the trader wants to receive after all
     * fees.
     */
    | {
        $case: "outputUnits";
        value: string;
      };
  /**
   * The address of integrator that will receive the fees on destination
   * blockchain.
   */
  integratorAddress?: ChainAddress | undefined;
  /** Integrator fee in percentage points (1/1,000,000 or 0.0001%). */
  integratorFeePips?: number | undefined;
  /**
   * Parameters of supported methods of the settlement.
   *
   * The protocol limits settlement methods in quotes to specified methods.
   * Different combinations of **Source** and **Destination** blockchains might
   * support different methods.
   */
  settlementParams: SettlementParams[];
}

/** A specific quote returned for an RFQ. */
export interface Quote {
  /** ID of the RFQ that initiated quote generation. */
  rfqId: string;
  /** ID of the quote generated by the platform. */
  quoteId: string;
  /** ID of the resolver. */
  resolverId: string;
  /** Name of the resolver. */
  resolverName: string;
  /** Blockchain-specific address of **Input asset**. */
  inputAsset: AssetId;
  /** Blockchain-specific address of **Output asset**. */
  outputAsset: AssetId;
  /**
   * The total amount of **Input asset** the trader will send, including all
   * fees.
   */
  inputUnits: string;
  /** The net amount of **Output asset** the trader will receive after all fees. */
  outputUnits: string;
  /**
   * The address of integrator that will receive the fees on destination
   * blockchain.
   */
  integratorAddress?: ChainAddress | undefined;
  /** The amount of fees that the integrator will get in **Output asset**. */
  integratorFeeUnits: string;
  /** The amount of fees charged by the protocol in **Output asset**. */
  protocolFeeUnits: string;
  /** The timestamp (UTC seconds) of Quote sent by resolver. */
  quoteTimestamp: number;
  /**
   * Additional settlement data.
   *
   * Swap settlement returns immediate routing data. Order settlement returns
   * data needed to create and later fill an order or position.
   */
  settlementData:
    | {
        $case: "swap";
        value: SwapSettlementData;
      }
    | {
        $case: "order";
        value: OrderSettlementData;
      };
  /**
   * Total gas budget on **Source blockchain** required to perform the trade.
   *
   * This parameter is omitted for gasless quotes.
   */
  gasBudget?: string | undefined;
  /**
   * Estimated amount of gas units that will be spent on **Source blockchain**
   * to perform the trade.
   *
   * This parameter is omitted for gasless quotes.
   */
  estimatedGasConsumption?: string | undefined;
}

function createBaseSwapSettlementParams(): SwapSettlementParams {
  return {
    maxPriceSlippagePips: undefined,
    maxRoutes: undefined,
    flexibleIntegratorFee: undefined,
    allowRiskyRoutes: undefined,
  };
}

export const SwapSettlementParams: MessageFns<SwapSettlementParams> = {
  fromJSON(object: any): SwapSettlementParams {
    return {
      maxPriceSlippagePips: isSet(object.max_price_slippage_pips)
        ? globalThis.Number(object.max_price_slippage_pips)
        : undefined,
      maxRoutes: isSet(object.max_routes) ? globalThis.Number(object.max_routes) : undefined,
      flexibleIntegratorFee: isSet(object.flexible_integrator_fee)
        ? globalThis.Boolean(object.flexible_integrator_fee)
        : undefined,
      allowRiskyRoutes: isSet(object.allow_risky_routes)
        ? globalThis.Boolean(object.allow_risky_routes)
        : undefined,
    };
  },

  toJSON(message: SwapSettlementParams): unknown {
    const obj: any = {};
    if (message.maxPriceSlippagePips !== undefined) {
      obj.max_price_slippage_pips = Math.round(message.maxPriceSlippagePips);
    }
    if (message.maxRoutes !== undefined) {
      obj.max_routes = Math.round(message.maxRoutes);
    }
    if (message.flexibleIntegratorFee !== undefined) {
      obj.flexible_integrator_fee = message.flexibleIntegratorFee;
    }
    if (message.allowRiskyRoutes !== undefined) {
      obj.allow_risky_routes = message.allowRiskyRoutes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapSettlementParams>, I>>(base?: I): SwapSettlementParams {
    return SwapSettlementParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapSettlementParams>, I>>(
    object: I,
  ): SwapSettlementParams {
    const message = createBaseSwapSettlementParams();
    message.maxPriceSlippagePips = object.maxPriceSlippagePips ?? undefined;
    message.maxRoutes = object.maxRoutes ?? undefined;
    message.flexibleIntegratorFee = object.flexibleIntegratorFee ?? undefined;
    message.allowRiskyRoutes = object.allowRiskyRoutes ?? undefined;
    return message;
  },
};

function createBaseOrderSettlementParams(): OrderSettlementParams {
  return {};
}

export const OrderSettlementParams: MessageFns<OrderSettlementParams> = {
  fromJSON(_: any): OrderSettlementParams {
    return {};
  },

  toJSON(_: OrderSettlementParams): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderSettlementParams>, I>>(base?: I): OrderSettlementParams {
    return OrderSettlementParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderSettlementParams>, I>>(_: I): OrderSettlementParams {
    const message = createBaseOrderSettlementParams();
    return message;
  },
};

function createBaseSettlementParams(): SettlementParams {
  return { params: undefined };
}

export const SettlementParams: MessageFns<SettlementParams> = {
  fromJSON(object: any): SettlementParams {
    return {
      params: isSet(object.swap)
        ? { $case: "swap", value: SwapSettlementParams.fromJSON(object.swap) }
        : isSet(object.order)
          ? { $case: "order", value: OrderSettlementParams.fromJSON(object.order) }
          : undefined,
    };
  },

  toJSON(message: SettlementParams): unknown {
    const obj: any = {};
    if (message.params?.$case === "swap") {
      obj.swap = SwapSettlementParams.toJSON(message.params.value);
    } else if (message.params?.$case === "order") {
      obj.order = OrderSettlementParams.toJSON(message.params.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SettlementParams>, I>>(base?: I): SettlementParams {
    return SettlementParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SettlementParams>, I>>(object: I): SettlementParams {
    const message = createBaseSettlementParams();
    switch (object.params?.$case) {
      case "swap": {
        if (object.params?.value !== undefined && object.params?.value !== null) {
          message.params = {
            $case: "swap",
            value: SwapSettlementParams.fromPartial(object.params.value),
          };
        }
        break;
      }
      case "order": {
        if (object.params?.value !== undefined && object.params?.value !== null) {
          message.params = {
            $case: "order",
            value: OrderSettlementParams.fromPartial(object.params.value),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseSwapSettlementData(): SwapSettlementData {
  return {
    routes: [],
    minOutputAmount: "",
    recommendedMinOutputAmount: "",
    recommendedSlippagePips: 0,
  };
}

export const SwapSettlementData: MessageFns<SwapSettlementData> = {
  fromJSON(object: any): SwapSettlementData {
    return {
      routes: globalThis.Array.isArray(object?.routes)
        ? object.routes.map((e: any) => SwapRoute.fromJSON(e))
        : [],
      minOutputAmount: isSet(object.min_output_amount)
        ? globalThis.String(object.min_output_amount)
        : "",
      recommendedMinOutputAmount: isSet(object.recommended_min_output_amount)
        ? globalThis.String(object.recommended_min_output_amount)
        : "",
      recommendedSlippagePips: isSet(object.recommended_slippage_pips)
        ? globalThis.Number(object.recommended_slippage_pips)
        : 0,
    };
  },

  toJSON(message: SwapSettlementData): unknown {
    const obj: any = {};
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => SwapRoute.toJSON(e));
    }
    if (message.minOutputAmount !== undefined) {
      obj.min_output_amount = message.minOutputAmount;
    }
    if (message.recommendedMinOutputAmount !== undefined) {
      obj.recommended_min_output_amount = message.recommendedMinOutputAmount;
    }
    if (message.recommendedSlippagePips !== undefined) {
      obj.recommended_slippage_pips = Math.round(message.recommendedSlippagePips);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapSettlementData>, I>>(base?: I): SwapSettlementData {
    return SwapSettlementData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapSettlementData>, I>>(object: I): SwapSettlementData {
    const message = createBaseSwapSettlementData();
    message.routes = object.routes?.map((e) => SwapRoute.fromPartial(e)) || [];
    message.minOutputAmount = object.minOutputAmount ?? "";
    message.recommendedMinOutputAmount = object.recommendedMinOutputAmount ?? "";
    message.recommendedSlippagePips = object.recommendedSlippagePips ?? 0;
    return message;
  },
};

function createBaseOrderSettlementData(): OrderSettlementData {
  return {
    srcProtocolContractAddress: undefined,
    srcWrappedNativeTokenAddress: undefined,
    srcInitialResolverAddress: undefined,
    srcHtlcSecurityDepositAsset: undefined,
    srcHtlcSecurityDepositUnits: undefined,
    htlcHashingFunction: undefined,
    dstProtocolContractAddress: undefined,
    resolverSendsUnits: "",
    dstWrappedNativeTokenAddress: undefined,
    dstSecurityDepositAsset: undefined,
    dstSecurityDepositUnits: undefined,
    tradeStartDeadline: 0,
    exclusivityTimeout: 0,
    integratorFeePips: 0,
    protocolFeePips: 0,
    protocolFeeRecipientAddress: undefined,
  };
}

export const OrderSettlementData: MessageFns<OrderSettlementData> = {
  fromJSON(object: any): OrderSettlementData {
    return {
      srcProtocolContractAddress: isSet(object.src_protocol_contract_address)
        ? ChainAddress.fromJSON(object.src_protocol_contract_address)
        : undefined,
      srcWrappedNativeTokenAddress: isSet(object.src_wrapped_native_token_address)
        ? ChainAddress.fromJSON(object.src_wrapped_native_token_address)
        : undefined,
      srcInitialResolverAddress: isSet(object.src_initial_resolver_address)
        ? ChainAddress.fromJSON(object.src_initial_resolver_address)
        : undefined,
      srcHtlcSecurityDepositAsset: isSet(object.src_htlc_security_deposit_asset)
        ? AssetId.fromJSON(object.src_htlc_security_deposit_asset)
        : undefined,
      srcHtlcSecurityDepositUnits: isSet(object.src_htlc_security_deposit_units)
        ? globalThis.String(object.src_htlc_security_deposit_units)
        : undefined,
      htlcHashingFunction: isSet(object.htlc_hashing_function)
        ? hashingFunctionFromJSON(object.htlc_hashing_function)
        : undefined,
      dstProtocolContractAddress: isSet(object.dst_protocol_contract_address)
        ? ChainAddress.fromJSON(object.dst_protocol_contract_address)
        : undefined,
      resolverSendsUnits: isSet(object.resolver_sends_units)
        ? globalThis.String(object.resolver_sends_units)
        : "",
      dstWrappedNativeTokenAddress: isSet(object.dst_wrapped_native_token_address)
        ? ChainAddress.fromJSON(object.dst_wrapped_native_token_address)
        : undefined,
      dstSecurityDepositAsset: isSet(object.dst_security_deposit_asset)
        ? AssetId.fromJSON(object.dst_security_deposit_asset)
        : undefined,
      dstSecurityDepositUnits: isSet(object.dst_security_deposit_units)
        ? globalThis.String(object.dst_security_deposit_units)
        : undefined,
      tradeStartDeadline: isSet(object.trade_start_deadline)
        ? globalThis.Number(object.trade_start_deadline)
        : 0,
      exclusivityTimeout: isSet(object.exclusivity_timeout)
        ? globalThis.Number(object.exclusivity_timeout)
        : 0,
      integratorFeePips: isSet(object.integrator_fee_pips)
        ? globalThis.Number(object.integrator_fee_pips)
        : 0,
      protocolFeePips: isSet(object.protocol_fee_pips)
        ? globalThis.Number(object.protocol_fee_pips)
        : 0,
      protocolFeeRecipientAddress: isSet(object.protocol_fee_recipient_address)
        ? ChainAddress.fromJSON(object.protocol_fee_recipient_address)
        : undefined,
    };
  },

  toJSON(message: OrderSettlementData): unknown {
    const obj: any = {};
    if (message.srcProtocolContractAddress !== undefined) {
      obj.src_protocol_contract_address = ChainAddress.toJSON(message.srcProtocolContractAddress);
    }
    if (message.srcWrappedNativeTokenAddress !== undefined) {
      obj.src_wrapped_native_token_address = ChainAddress.toJSON(
        message.srcWrappedNativeTokenAddress,
      );
    }
    if (message.srcInitialResolverAddress !== undefined) {
      obj.src_initial_resolver_address = ChainAddress.toJSON(message.srcInitialResolverAddress);
    }
    if (message.srcHtlcSecurityDepositAsset !== undefined) {
      obj.src_htlc_security_deposit_asset = AssetId.toJSON(message.srcHtlcSecurityDepositAsset);
    }
    if (message.srcHtlcSecurityDepositUnits !== undefined) {
      obj.src_htlc_security_deposit_units = message.srcHtlcSecurityDepositUnits;
    }
    if (message.htlcHashingFunction !== undefined) {
      obj.htlc_hashing_function = hashingFunctionToJSON(message.htlcHashingFunction);
    }
    if (message.dstProtocolContractAddress !== undefined) {
      obj.dst_protocol_contract_address = ChainAddress.toJSON(message.dstProtocolContractAddress);
    }
    if (message.resolverSendsUnits !== undefined) {
      obj.resolver_sends_units = message.resolverSendsUnits;
    }
    if (message.dstWrappedNativeTokenAddress !== undefined) {
      obj.dst_wrapped_native_token_address = ChainAddress.toJSON(
        message.dstWrappedNativeTokenAddress,
      );
    }
    if (message.dstSecurityDepositAsset !== undefined) {
      obj.dst_security_deposit_asset = AssetId.toJSON(message.dstSecurityDepositAsset);
    }
    if (message.dstSecurityDepositUnits !== undefined) {
      obj.dst_security_deposit_units = message.dstSecurityDepositUnits;
    }
    if (message.tradeStartDeadline !== undefined) {
      obj.trade_start_deadline = Math.round(message.tradeStartDeadline);
    }
    if (message.exclusivityTimeout !== undefined) {
      obj.exclusivity_timeout = Math.round(message.exclusivityTimeout);
    }
    if (message.integratorFeePips !== undefined) {
      obj.integrator_fee_pips = Math.round(message.integratorFeePips);
    }
    if (message.protocolFeePips !== undefined) {
      obj.protocol_fee_pips = Math.round(message.protocolFeePips);
    }
    if (message.protocolFeeRecipientAddress !== undefined) {
      obj.protocol_fee_recipient_address = ChainAddress.toJSON(message.protocolFeeRecipientAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderSettlementData>, I>>(base?: I): OrderSettlementData {
    return OrderSettlementData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderSettlementData>, I>>(
    object: I,
  ): OrderSettlementData {
    const message = createBaseOrderSettlementData();
    message.srcProtocolContractAddress =
      object.srcProtocolContractAddress !== undefined && object.srcProtocolContractAddress !== null
        ? ChainAddress.fromPartial(object.srcProtocolContractAddress)
        : undefined;
    message.srcWrappedNativeTokenAddress =
      object.srcWrappedNativeTokenAddress !== undefined &&
      object.srcWrappedNativeTokenAddress !== null
        ? ChainAddress.fromPartial(object.srcWrappedNativeTokenAddress)
        : undefined;
    message.srcInitialResolverAddress =
      object.srcInitialResolverAddress !== undefined && object.srcInitialResolverAddress !== null
        ? ChainAddress.fromPartial(object.srcInitialResolverAddress)
        : undefined;
    message.srcHtlcSecurityDepositAsset =
      object.srcHtlcSecurityDepositAsset !== undefined &&
      object.srcHtlcSecurityDepositAsset !== null
        ? AssetId.fromPartial(object.srcHtlcSecurityDepositAsset)
        : undefined;
    message.srcHtlcSecurityDepositUnits = object.srcHtlcSecurityDepositUnits ?? undefined;
    message.htlcHashingFunction = object.htlcHashingFunction ?? undefined;
    message.dstProtocolContractAddress =
      object.dstProtocolContractAddress !== undefined && object.dstProtocolContractAddress !== null
        ? ChainAddress.fromPartial(object.dstProtocolContractAddress)
        : undefined;
    message.resolverSendsUnits = object.resolverSendsUnits ?? "";
    message.dstWrappedNativeTokenAddress =
      object.dstWrappedNativeTokenAddress !== undefined &&
      object.dstWrappedNativeTokenAddress !== null
        ? ChainAddress.fromPartial(object.dstWrappedNativeTokenAddress)
        : undefined;
    message.dstSecurityDepositAsset =
      object.dstSecurityDepositAsset !== undefined && object.dstSecurityDepositAsset !== null
        ? AssetId.fromPartial(object.dstSecurityDepositAsset)
        : undefined;
    message.dstSecurityDepositUnits = object.dstSecurityDepositUnits ?? undefined;
    message.tradeStartDeadline = object.tradeStartDeadline ?? 0;
    message.exclusivityTimeout = object.exclusivityTimeout ?? 0;
    message.integratorFeePips = object.integratorFeePips ?? 0;
    message.protocolFeePips = object.protocolFeePips ?? 0;
    message.protocolFeeRecipientAddress =
      object.protocolFeeRecipientAddress !== undefined &&
      object.protocolFeeRecipientAddress !== null
        ? ChainAddress.fromPartial(object.protocolFeeRecipientAddress)
        : undefined;
    return message;
  },
};

function createBaseQuoteRequest(): QuoteRequest {
  return {
    inputAsset: undefined,
    outputAsset: undefined,
    amount: undefined,
    integratorAddress: undefined,
    integratorFeePips: undefined,
    settlementParams: [],
  };
}

export const QuoteRequest: MessageFns<QuoteRequest> = {
  fromJSON(object: any): QuoteRequest {
    return {
      inputAsset: isSet(object.input_asset) ? AssetId.fromJSON(object.input_asset) : undefined,
      outputAsset: isSet(object.output_asset) ? AssetId.fromJSON(object.output_asset) : undefined,
      amount: isSet(object.input_units)
        ? { $case: "inputUnits", value: globalThis.String(object.input_units) }
        : isSet(object.output_units)
          ? { $case: "outputUnits", value: globalThis.String(object.output_units) }
          : undefined,
      integratorAddress: isSet(object.integrator_address)
        ? ChainAddress.fromJSON(object.integrator_address)
        : undefined,
      integratorFeePips: isSet(object.integrator_fee_pips)
        ? globalThis.Number(object.integrator_fee_pips)
        : undefined,
      settlementParams: globalThis.Array.isArray(object?.settlement_params)
        ? object.settlement_params.map((e: any) => SettlementParams.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QuoteRequest): unknown {
    const obj: any = {};
    if (message.inputAsset !== undefined) {
      obj.input_asset = AssetId.toJSON(message.inputAsset);
    }
    if (message.outputAsset !== undefined) {
      obj.output_asset = AssetId.toJSON(message.outputAsset);
    }
    if (message.amount?.$case === "inputUnits") {
      obj.input_units = message.amount.value;
    } else if (message.amount?.$case === "outputUnits") {
      obj.output_units = message.amount.value;
    }
    if (message.integratorAddress !== undefined) {
      obj.integrator_address = ChainAddress.toJSON(message.integratorAddress);
    }
    if (message.integratorFeePips !== undefined) {
      obj.integrator_fee_pips = Math.round(message.integratorFeePips);
    }
    if (message.settlementParams?.length) {
      obj.settlement_params = message.settlementParams.map((e) => SettlementParams.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuoteRequest>, I>>(base?: I): QuoteRequest {
    return QuoteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuoteRequest>, I>>(object: I): QuoteRequest {
    const message = createBaseQuoteRequest();
    message.inputAsset =
      object.inputAsset !== undefined && object.inputAsset !== null
        ? AssetId.fromPartial(object.inputAsset)
        : undefined;
    message.outputAsset =
      object.outputAsset !== undefined && object.outputAsset !== null
        ? AssetId.fromPartial(object.outputAsset)
        : undefined;
    switch (object.amount?.$case) {
      case "inputUnits": {
        if (object.amount?.value !== undefined && object.amount?.value !== null) {
          message.amount = { $case: "inputUnits", value: object.amount.value };
        }
        break;
      }
      case "outputUnits": {
        if (object.amount?.value !== undefined && object.amount?.value !== null) {
          message.amount = { $case: "outputUnits", value: object.amount.value };
        }
        break;
      }
    }
    message.integratorAddress =
      object.integratorAddress !== undefined && object.integratorAddress !== null
        ? ChainAddress.fromPartial(object.integratorAddress)
        : undefined;
    message.integratorFeePips = object.integratorFeePips ?? undefined;
    message.settlementParams =
      object.settlementParams?.map((e) => SettlementParams.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQuote(): Quote {
  return {
    rfqId: "",
    quoteId: "",
    resolverId: "",
    resolverName: "",
    inputAsset: undefined,
    outputAsset: undefined,
    inputUnits: "",
    outputUnits: "",
    integratorAddress: undefined,
    integratorFeeUnits: "",
    protocolFeeUnits: "",
    quoteTimestamp: 0,
    settlementData: undefined,
    gasBudget: undefined,
    estimatedGasConsumption: undefined,
  };
}

export const Quote: MessageFns<Quote> = {
  fromJSON(object: any): Quote {
    return {
      rfqId: isSet(object.rfq_id) ? globalThis.String(object.rfq_id) : "",
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      resolverId: isSet(object.resolver_id) ? globalThis.String(object.resolver_id) : "",
      resolverName: isSet(object.resolver_name) ? globalThis.String(object.resolver_name) : "",
      inputAsset: isSet(object.input_asset) ? AssetId.fromJSON(object.input_asset) : undefined,
      outputAsset: isSet(object.output_asset) ? AssetId.fromJSON(object.output_asset) : undefined,
      inputUnits: isSet(object.input_units) ? globalThis.String(object.input_units) : "",
      outputUnits: isSet(object.output_units) ? globalThis.String(object.output_units) : "",
      integratorAddress: isSet(object.integrator_address)
        ? ChainAddress.fromJSON(object.integrator_address)
        : undefined,
      integratorFeeUnits: isSet(object.integrator_fee_units)
        ? globalThis.String(object.integrator_fee_units)
        : "",
      protocolFeeUnits: isSet(object.protocol_fee_units)
        ? globalThis.String(object.protocol_fee_units)
        : "",
      quoteTimestamp: isSet(object.quote_timestamp) ? globalThis.Number(object.quote_timestamp) : 0,
      settlementData: isSet(object.swap)
        ? { $case: "swap", value: SwapSettlementData.fromJSON(object.swap) }
        : isSet(object.order)
          ? { $case: "order", value: OrderSettlementData.fromJSON(object.order) }
          : undefined,
      gasBudget: isSet(object.gas_budget) ? globalThis.String(object.gas_budget) : undefined,
      estimatedGasConsumption: isSet(object.estimated_gas_consumption)
        ? globalThis.String(object.estimated_gas_consumption)
        : undefined,
    };
  },

  toJSON(message: Quote): unknown {
    const obj: any = {};
    if (message.rfqId !== undefined) {
      obj.rfq_id = message.rfqId;
    }
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.resolverId !== undefined) {
      obj.resolver_id = message.resolverId;
    }
    if (message.resolverName !== undefined) {
      obj.resolver_name = message.resolverName;
    }
    if (message.inputAsset !== undefined) {
      obj.input_asset = AssetId.toJSON(message.inputAsset);
    }
    if (message.outputAsset !== undefined) {
      obj.output_asset = AssetId.toJSON(message.outputAsset);
    }
    if (message.inputUnits !== undefined) {
      obj.input_units = message.inputUnits;
    }
    if (message.outputUnits !== undefined) {
      obj.output_units = message.outputUnits;
    }
    if (message.integratorAddress !== undefined) {
      obj.integrator_address = ChainAddress.toJSON(message.integratorAddress);
    }
    if (message.integratorFeeUnits !== undefined) {
      obj.integrator_fee_units = message.integratorFeeUnits;
    }
    if (message.protocolFeeUnits !== undefined) {
      obj.protocol_fee_units = message.protocolFeeUnits;
    }
    if (message.quoteTimestamp !== undefined) {
      obj.quote_timestamp = Math.round(message.quoteTimestamp);
    }
    if (message.settlementData?.$case === "swap") {
      obj.swap = SwapSettlementData.toJSON(message.settlementData.value);
    } else if (message.settlementData?.$case === "order") {
      obj.order = OrderSettlementData.toJSON(message.settlementData.value);
    }
    if (message.gasBudget !== undefined) {
      obj.gas_budget = message.gasBudget;
    }
    if (message.estimatedGasConsumption !== undefined) {
      obj.estimated_gas_consumption = message.estimatedGasConsumption;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Quote>, I>>(base?: I): Quote {
    return Quote.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Quote>, I>>(object: I): Quote {
    const message = createBaseQuote();
    message.rfqId = object.rfqId ?? "";
    message.quoteId = object.quoteId ?? "";
    message.resolverId = object.resolverId ?? "";
    message.resolverName = object.resolverName ?? "";
    message.inputAsset =
      object.inputAsset !== undefined && object.inputAsset !== null
        ? AssetId.fromPartial(object.inputAsset)
        : undefined;
    message.outputAsset =
      object.outputAsset !== undefined && object.outputAsset !== null
        ? AssetId.fromPartial(object.outputAsset)
        : undefined;
    message.inputUnits = object.inputUnits ?? "";
    message.outputUnits = object.outputUnits ?? "";
    message.integratorAddress =
      object.integratorAddress !== undefined && object.integratorAddress !== null
        ? ChainAddress.fromPartial(object.integratorAddress)
        : undefined;
    message.integratorFeeUnits = object.integratorFeeUnits ?? "";
    message.protocolFeeUnits = object.protocolFeeUnits ?? "";
    message.quoteTimestamp = object.quoteTimestamp ?? 0;
    switch (object.settlementData?.$case) {
      case "swap": {
        if (object.settlementData?.value !== undefined && object.settlementData?.value !== null) {
          message.settlementData = {
            $case: "swap",
            value: SwapSettlementData.fromPartial(object.settlementData.value),
          };
        }
        break;
      }
      case "order": {
        if (object.settlementData?.value !== undefined && object.settlementData?.value !== null) {
          message.settlementData = {
            $case: "order",
            value: OrderSettlementData.fromPartial(object.settlementData.value),
          };
        }
        break;
      }
    }
    message.gasBudget = object.gasBudget ?? undefined;
    message.estimatedGasConsumption = object.estimatedGasConsumption ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
