// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/types/swap.proto

// @ts-nocheck
// oxlint-disable

import { AssetId } from "../../../common/v1/types/asset_id";
import { ChainAddress } from "../../../common/v1/types/chain_address";
import { KeepAlive, TradeStatus, tradeStatusFromJSON, tradeStatusToJSON } from "./common";

/** Result of a single swap chunk execution. */
export const SwapChunkResult = {
  SWAP_CHUNK_RESULT_PROCESSING: "SWAP_CHUNK_RESULT_PROCESSING",
  SWAP_CHUNK_RESULT_FILLED: "SWAP_CHUNK_RESULT_FILLED",
  SWAP_CHUNK_RESULT_ABORTED: "SWAP_CHUNK_RESULT_ABORTED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type SwapChunkResult = (typeof SwapChunkResult)[keyof typeof SwapChunkResult];

export namespace SwapChunkResult {
  export type SWAP_CHUNK_RESULT_PROCESSING = typeof SwapChunkResult.SWAP_CHUNK_RESULT_PROCESSING;
  export type SWAP_CHUNK_RESULT_FILLED = typeof SwapChunkResult.SWAP_CHUNK_RESULT_FILLED;
  export type SWAP_CHUNK_RESULT_ABORTED = typeof SwapChunkResult.SWAP_CHUNK_RESULT_ABORTED;
  export type UNRECOGNIZED = typeof SwapChunkResult.UNRECOGNIZED;
}

export function swapChunkResultFromJSON(object: any): SwapChunkResult {
  switch (object) {
    case 0:
    case "SWAP_CHUNK_RESULT_PROCESSING":
      return SwapChunkResult.SWAP_CHUNK_RESULT_PROCESSING;
    case 1:
    case "SWAP_CHUNK_RESULT_FILLED":
      return SwapChunkResult.SWAP_CHUNK_RESULT_FILLED;
    case 2:
    case "SWAP_CHUNK_RESULT_ABORTED":
      return SwapChunkResult.SWAP_CHUNK_RESULT_ABORTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SwapChunkResult.UNRECOGNIZED;
  }
}

export function swapChunkResultToJSON(object: SwapChunkResult): number {
  switch (object) {
    case SwapChunkResult.SWAP_CHUNK_RESULT_PROCESSING:
      return 0;
    case SwapChunkResult.SWAP_CHUNK_RESULT_FILLED:
      return 1;
    case SwapChunkResult.SWAP_CHUNK_RESULT_ABORTED:
      return 2;
    case SwapChunkResult.UNRECOGNIZED:
    default:
      return -1;
  }
}

/**
 * Represents route of swapping assets: `TON -> USDT`, `TON -> USDC -> USDT`,
 * etc.
 */
export interface SwapRoute {
  steps: SwapStep[];
}

/**
 * Represents a single step in a route: `TON -> USDC -> USDT` route consists of
 * `TON -> USDC` & `USDC -> USDT` steps.
 */
export interface SwapStep {
  inputAsset: AssetId;
  outputAsset: AssetId;
  chunks: SwapChunk[];
}

/**
 * Represents a single swap tx in a step: `TON -> USDT` swap might consist of
 * two chunks utilizing different protocols.
 */
export interface SwapChunk {
  protocol: string;
  inputUnits: string;
  outputUnits: string;
}

/** Progress details of a single swap chunk. */
export interface SwapChunkProgress {
  protocol: string;
  /**
   * Address of the contract that processes this chunk.
   *
   * Generally, this address receives input tokens.
   * More specifically, it might be the address of a protocol or liquidity pool.
   */
  targetAddress: ChainAddress;
  inputUnits: string;
  expectedOutputUnits: string;
  actualOutputUnits: string;
  result: SwapChunkResult;
  /** Hash of the transaction that performs swapping of the chunk. */
  txHash: string;
}

/** Progress details of a single swap step. */
export interface SwapStepProgress {
  chunks: SwapChunkProgress[];
}

/** Progress details of an entire swap route. */
export interface SwapRouteProgress {
  steps: SwapStepProgress[];
}

/** Aggregated progress of the whole swap. */
export interface SwapProgress {
  /** Status of the trade */
  status: TradeStatus;
  outgoingTxHash: string;
  routes: SwapRouteProgress[];
  transferTimestamp?: number | undefined;
  estimatedFinishTimestamp?: number | undefined;
}

export interface AwaitingTransfer {}

/** One event in the swap-progress stream. */
export interface SwapProgressEvent {
  event:
    | {
        $case: "awaitingTransfer";
        value: AwaitingTransfer;
      }
    | {
        $case: "progress";
        value: SwapProgress;
      } //
    /** The service message to keep connection alive */
    | {
        $case: "keepAlive";
        value: KeepAlive;
      };
}

function createBaseSwapRoute(): SwapRoute {
  return { steps: [] };
}

export const SwapRoute: MessageFns<SwapRoute> = {
  fromJSON(object: any): SwapRoute {
    return {
      steps: globalThis.Array.isArray(object?.steps)
        ? object.steps.map((e: any) => SwapStep.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SwapRoute): unknown {
    const obj: any = {};
    if (message.steps?.length) {
      obj.steps = message.steps.map((e) => SwapStep.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapRoute>, I>>(base?: I): SwapRoute {
    return SwapRoute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapRoute>, I>>(object: I): SwapRoute {
    const message = createBaseSwapRoute();
    message.steps = object.steps?.map((e) => SwapStep.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSwapStep(): SwapStep {
  return { inputAsset: undefined, outputAsset: undefined, chunks: [] };
}

export const SwapStep: MessageFns<SwapStep> = {
  fromJSON(object: any): SwapStep {
    return {
      inputAsset: isSet(object.input_asset) ? AssetId.fromJSON(object.input_asset) : undefined,
      outputAsset: isSet(object.output_asset) ? AssetId.fromJSON(object.output_asset) : undefined,
      chunks: globalThis.Array.isArray(object?.chunks)
        ? object.chunks.map((e: any) => SwapChunk.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SwapStep): unknown {
    const obj: any = {};
    if (message.inputAsset !== undefined) {
      obj.input_asset = AssetId.toJSON(message.inputAsset);
    }
    if (message.outputAsset !== undefined) {
      obj.output_asset = AssetId.toJSON(message.outputAsset);
    }
    if (message.chunks?.length) {
      obj.chunks = message.chunks.map((e) => SwapChunk.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapStep>, I>>(base?: I): SwapStep {
    return SwapStep.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapStep>, I>>(object: I): SwapStep {
    const message = createBaseSwapStep();
    message.inputAsset =
      object.inputAsset !== undefined && object.inputAsset !== null
        ? AssetId.fromPartial(object.inputAsset)
        : undefined;
    message.outputAsset =
      object.outputAsset !== undefined && object.outputAsset !== null
        ? AssetId.fromPartial(object.outputAsset)
        : undefined;
    message.chunks = object.chunks?.map((e) => SwapChunk.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSwapChunk(): SwapChunk {
  return { protocol: "", inputUnits: "", outputUnits: "" };
}

export const SwapChunk: MessageFns<SwapChunk> = {
  fromJSON(object: any): SwapChunk {
    return {
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
      inputUnits: isSet(object.input_units) ? globalThis.String(object.input_units) : "",
      outputUnits: isSet(object.output_units) ? globalThis.String(object.output_units) : "",
    };
  },

  toJSON(message: SwapChunk): unknown {
    const obj: any = {};
    if (message.protocol !== undefined) {
      obj.protocol = message.protocol;
    }
    if (message.inputUnits !== undefined) {
      obj.input_units = message.inputUnits;
    }
    if (message.outputUnits !== undefined) {
      obj.output_units = message.outputUnits;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapChunk>, I>>(base?: I): SwapChunk {
    return SwapChunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapChunk>, I>>(object: I): SwapChunk {
    const message = createBaseSwapChunk();
    message.protocol = object.protocol ?? "";
    message.inputUnits = object.inputUnits ?? "";
    message.outputUnits = object.outputUnits ?? "";
    return message;
  },
};

function createBaseSwapChunkProgress(): SwapChunkProgress {
  return {
    protocol: "",
    targetAddress: undefined,
    inputUnits: "",
    expectedOutputUnits: "",
    actualOutputUnits: "",
    result: SwapChunkResult.SWAP_CHUNK_RESULT_PROCESSING,
    txHash: "",
  };
}

export const SwapChunkProgress: MessageFns<SwapChunkProgress> = {
  fromJSON(object: any): SwapChunkProgress {
    return {
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : "",
      targetAddress: isSet(object.target_address)
        ? ChainAddress.fromJSON(object.target_address)
        : undefined,
      inputUnits: isSet(object.input_units) ? globalThis.String(object.input_units) : "",
      expectedOutputUnits: isSet(object.expected_output_units)
        ? globalThis.String(object.expected_output_units)
        : "",
      actualOutputUnits: isSet(object.actual_output_units)
        ? globalThis.String(object.actual_output_units)
        : "",
      result: isSet(object.result)
        ? swapChunkResultFromJSON(object.result)
        : SwapChunkResult.SWAP_CHUNK_RESULT_PROCESSING,
      txHash: isSet(object.tx_hash) ? globalThis.String(object.tx_hash) : "",
    };
  },

  toJSON(message: SwapChunkProgress): unknown {
    const obj: any = {};
    if (message.protocol !== undefined) {
      obj.protocol = message.protocol;
    }
    if (message.targetAddress !== undefined) {
      obj.target_address = ChainAddress.toJSON(message.targetAddress);
    }
    if (message.inputUnits !== undefined) {
      obj.input_units = message.inputUnits;
    }
    if (message.expectedOutputUnits !== undefined) {
      obj.expected_output_units = message.expectedOutputUnits;
    }
    if (message.actualOutputUnits !== undefined) {
      obj.actual_output_units = message.actualOutputUnits;
    }
    if (message.result !== undefined) {
      obj.result = swapChunkResultToJSON(message.result);
    }
    if (message.txHash !== undefined) {
      obj.tx_hash = message.txHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapChunkProgress>, I>>(base?: I): SwapChunkProgress {
    return SwapChunkProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapChunkProgress>, I>>(object: I): SwapChunkProgress {
    const message = createBaseSwapChunkProgress();
    message.protocol = object.protocol ?? "";
    message.targetAddress =
      object.targetAddress !== undefined && object.targetAddress !== null
        ? ChainAddress.fromPartial(object.targetAddress)
        : undefined;
    message.inputUnits = object.inputUnits ?? "";
    message.expectedOutputUnits = object.expectedOutputUnits ?? "";
    message.actualOutputUnits = object.actualOutputUnits ?? "";
    message.result = object.result ?? SwapChunkResult.SWAP_CHUNK_RESULT_PROCESSING;
    message.txHash = object.txHash ?? "";
    return message;
  },
};

function createBaseSwapStepProgress(): SwapStepProgress {
  return { chunks: [] };
}

export const SwapStepProgress: MessageFns<SwapStepProgress> = {
  fromJSON(object: any): SwapStepProgress {
    return {
      chunks: globalThis.Array.isArray(object?.chunks)
        ? object.chunks.map((e: any) => SwapChunkProgress.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SwapStepProgress): unknown {
    const obj: any = {};
    if (message.chunks?.length) {
      obj.chunks = message.chunks.map((e) => SwapChunkProgress.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapStepProgress>, I>>(base?: I): SwapStepProgress {
    return SwapStepProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapStepProgress>, I>>(object: I): SwapStepProgress {
    const message = createBaseSwapStepProgress();
    message.chunks = object.chunks?.map((e) => SwapChunkProgress.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSwapRouteProgress(): SwapRouteProgress {
  return { steps: [] };
}

export const SwapRouteProgress: MessageFns<SwapRouteProgress> = {
  fromJSON(object: any): SwapRouteProgress {
    return {
      steps: globalThis.Array.isArray(object?.steps)
        ? object.steps.map((e: any) => SwapStepProgress.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SwapRouteProgress): unknown {
    const obj: any = {};
    if (message.steps?.length) {
      obj.steps = message.steps.map((e) => SwapStepProgress.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapRouteProgress>, I>>(base?: I): SwapRouteProgress {
    return SwapRouteProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapRouteProgress>, I>>(object: I): SwapRouteProgress {
    const message = createBaseSwapRouteProgress();
    message.steps = object.steps?.map((e) => SwapStepProgress.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSwapProgress(): SwapProgress {
  return {
    status: TradeStatus.TRADE_STATUS_IN_PROGRESS,
    outgoingTxHash: "",
    routes: [],
    transferTimestamp: undefined,
    estimatedFinishTimestamp: undefined,
  };
}

export const SwapProgress: MessageFns<SwapProgress> = {
  fromJSON(object: any): SwapProgress {
    return {
      status: isSet(object.status)
        ? tradeStatusFromJSON(object.status)
        : TradeStatus.TRADE_STATUS_IN_PROGRESS,
      outgoingTxHash: isSet(object.outgoing_tx_hash)
        ? globalThis.String(object.outgoing_tx_hash)
        : "",
      routes: globalThis.Array.isArray(object?.routes)
        ? object.routes.map((e: any) => SwapRouteProgress.fromJSON(e))
        : [],
      transferTimestamp: isSet(object.transfer_timestamp)
        ? globalThis.Number(object.transfer_timestamp)
        : undefined,
      estimatedFinishTimestamp: isSet(object.estimated_finish_timestamp)
        ? globalThis.Number(object.estimated_finish_timestamp)
        : undefined,
    };
  },

  toJSON(message: SwapProgress): unknown {
    const obj: any = {};
    if (message.status !== undefined) {
      obj.status = tradeStatusToJSON(message.status);
    }
    if (message.outgoingTxHash !== undefined) {
      obj.outgoing_tx_hash = message.outgoingTxHash;
    }
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => SwapRouteProgress.toJSON(e));
    }
    if (message.transferTimestamp !== undefined) {
      obj.transfer_timestamp = Math.round(message.transferTimestamp);
    }
    if (message.estimatedFinishTimestamp !== undefined) {
      obj.estimated_finish_timestamp = Math.round(message.estimatedFinishTimestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapProgress>, I>>(base?: I): SwapProgress {
    return SwapProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapProgress>, I>>(object: I): SwapProgress {
    const message = createBaseSwapProgress();
    message.status = object.status ?? TradeStatus.TRADE_STATUS_IN_PROGRESS;
    message.outgoingTxHash = object.outgoingTxHash ?? "";
    message.routes = object.routes?.map((e) => SwapRouteProgress.fromPartial(e)) || [];
    message.transferTimestamp = object.transferTimestamp ?? undefined;
    message.estimatedFinishTimestamp = object.estimatedFinishTimestamp ?? undefined;
    return message;
  },
};

function createBaseAwaitingTransfer(): AwaitingTransfer {
  return {};
}

export const AwaitingTransfer: MessageFns<AwaitingTransfer> = {
  fromJSON(_: any): AwaitingTransfer {
    return {};
  },

  toJSON(_: AwaitingTransfer): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<AwaitingTransfer>, I>>(base?: I): AwaitingTransfer {
    return AwaitingTransfer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AwaitingTransfer>, I>>(_: I): AwaitingTransfer {
    const message = createBaseAwaitingTransfer();
    return message;
  },
};

function createBaseSwapProgressEvent(): SwapProgressEvent {
  return { event: undefined };
}

export const SwapProgressEvent: MessageFns<SwapProgressEvent> = {
  fromJSON(object: any): SwapProgressEvent {
    return {
      event: isSet(object.awaiting_transfer)
        ? { $case: "awaitingTransfer", value: AwaitingTransfer.fromJSON(object.awaiting_transfer) }
        : isSet(object.progress)
          ? { $case: "progress", value: SwapProgress.fromJSON(object.progress) }
          : isSet(object.keep_alive)
            ? { $case: "keepAlive", value: KeepAlive.fromJSON(object.keep_alive) }
            : undefined,
    };
  },

  toJSON(message: SwapProgressEvent): unknown {
    const obj: any = {};
    if (message.event?.$case === "awaitingTransfer") {
      obj.awaiting_transfer = AwaitingTransfer.toJSON(message.event.value);
    } else if (message.event?.$case === "progress") {
      obj.progress = SwapProgress.toJSON(message.event.value);
    } else if (message.event?.$case === "keepAlive") {
      obj.keep_alive = KeepAlive.toJSON(message.event.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwapProgressEvent>, I>>(base?: I): SwapProgressEvent {
    return SwapProgressEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwapProgressEvent>, I>>(object: I): SwapProgressEvent {
    const message = createBaseSwapProgressEvent();
    switch (object.event?.$case) {
      case "awaitingTransfer": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = {
            $case: "awaitingTransfer",
            value: AwaitingTransfer.fromPartial(object.event.value),
          };
        }
        break;
      }
      case "progress": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = {
            $case: "progress",
            value: SwapProgress.fromPartial(object.event.value),
          };
        }
        break;
      }
      case "keepAlive": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = { $case: "keepAlive", value: KeepAlive.fromPartial(object.event.value) };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
