// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/types/ton.proto

// @ts-nocheck
// oxlint-disable

/**
 * A single outbound message to be sent on TON blockchain as part of a
 * transaction.
 *
 * The payload is typically a BoC-serialized cell represented as a hex string.
 * For jetton transfers, `jetton_wallet_state_init` may be provided to allow
 * deploying the jetton wallet on first use.
 */
export interface TonMessage {
  /** Target contract address that should receive this message. */
  targetAddress: string;
  /**
   * Amount of TON (in nanotons) to attach as the send value.
   *
   * This amount usually covers gas and, when applicable, forwarded TON for
   * inner calls.
   */
  sendAmount: string;
  /** Message body payload (BoC), encoded as a hex string. */
  payload: string;
  /**
   * Optional state init for the jetton wallet contract (BoC), encoded as a hex
   * string.
   *
   * If provided, the wallet can be deployed along with the first transfer.
   */
  jettonWalletStateInit?: string | undefined;
}

/**
 * A TON transaction composed of one or more outbound messages.
 *
 * Messages are expected to be sent by the same sender wallet in the given
 * order.
 */
export interface TonTransaction {
  /**
   * Ordered list of outbound messages to execute within a single wallet
   * transaction.
   */
  messages: TonMessage[];
}

function createBaseTonMessage(): TonMessage {
  return { targetAddress: "", sendAmount: "", payload: "", jettonWalletStateInit: undefined };
}

export const TonMessage: MessageFns<TonMessage> = {
  fromJSON(object: any): TonMessage {
    return {
      targetAddress: isSet(object.target_address) ? globalThis.String(object.target_address) : "",
      sendAmount: isSet(object.send_amount) ? globalThis.String(object.send_amount) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
      jettonWalletStateInit: isSet(object.jetton_wallet_state_init)
        ? globalThis.String(object.jetton_wallet_state_init)
        : undefined,
    };
  },

  toJSON(message: TonMessage): unknown {
    const obj: any = {};
    if (message.targetAddress !== undefined) {
      obj.target_address = message.targetAddress;
    }
    if (message.sendAmount !== undefined) {
      obj.send_amount = message.sendAmount;
    }
    if (message.payload !== undefined) {
      obj.payload = message.payload;
    }
    if (message.jettonWalletStateInit !== undefined) {
      obj.jetton_wallet_state_init = message.jettonWalletStateInit;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonMessage>, I>>(base?: I): TonMessage {
    return TonMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonMessage>, I>>(object: I): TonMessage {
    const message = createBaseTonMessage();
    message.targetAddress = object.targetAddress ?? "";
    message.sendAmount = object.sendAmount ?? "";
    message.payload = object.payload ?? "";
    message.jettonWalletStateInit = object.jettonWalletStateInit ?? undefined;
    return message;
  },
};

function createBaseTonTransaction(): TonTransaction {
  return { messages: [] };
}

export const TonTransaction: MessageFns<TonTransaction> = {
  fromJSON(object: any): TonTransaction {
    return {
      messages: globalThis.Array.isArray(object?.messages)
        ? object.messages.map((e: any) => TonMessage.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TonTransaction): unknown {
    const obj: any = {};
    if (message.messages?.length) {
      obj.messages = message.messages.map((e) => TonMessage.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonTransaction>, I>>(base?: I): TonTransaction {
    return TonTransaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonTransaction>, I>>(object: I): TonTransaction {
    const message = createBaseTonTransaction();
    message.messages = object.messages?.map((e) => TonMessage.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
