minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - "@ston-fi/*"

onlyBuiltDependencies:
  - "lefthook"

packages:
  - "examples/*"
  - "packages/*"

verifyDepsBeforeRun: "install"

catalog:
  "@arethetypeswrong/cli": 0.18.2
  "publint": 0.3.18
  "vitest": 4.0.18
  "rxjs": 7.8.2
  "tsdown": 0.21.7
