// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.0
//   protoc               v6.33.0
// source: omni/v1beta7/types/gasless.proto

/* eslint-disable */
//biome-ignore-all : autogenerated file, no need to check

export const protobufPackage = "omni.v1beta7";

/**
 * TODO: unstable API
 * TODO: finalize when WalletW5 extension will be finalized
 */
export interface TonGaslessPayload {
  /** Base64 serialized cell for signing with TON Connect. */
  cell: string;
  /** TL-B schema of payload cell. */
  schema: string;
}

/**
 * TODO: unstable API
 * Payload of gasless order for signing
 */
export interface GaslessPayload {
  gaslessPayload: GaslessPayload_GaslessPayloadOneOf | undefined;
}

export interface GaslessPayload_GaslessPayloadOneOf {
  ton?: TonGaslessPayload | undefined;
}

/** TODO: unstable API */
export interface TonGaslessOrder {
  /** Address of TON wallet that signed the message with signData method. */
  walletAddress: string;
  /** Timestamp of signing returned by TonConnect's signData method. */
  timestamp: number;
  /** Domain returned by TonConnect's signData method. */
  domain: string;
  /** Base64 serialized cell signed with TonConnect's signData. */
  payload: string;
  /** Base64 signature returned by TonConnect's signData method. */
  signature: string;
}

/**
 * TODO: unstable API
 * Signed gasless order
 */
export interface GaslessOrder {
  gaslessOrder: GaslessOrder_GaslessOrderOneOf | undefined;
}

export interface GaslessOrder_GaslessOrderOneOf {
  ton?: TonGaslessOrder | undefined;
}

/**
 * TODO: unstable API
 * Contains text 'CANCEL <QUOTE-ID-HEX>' signed with TonConnect's signData method.
 */
export interface TonGaslessCancellation {
  /** Address of TON wallet that signed the cancellation message with signData method. */
  walletAddress: string;
  /** Timestamp of signing returned by TonConnect's signData method. */
  timestamp: number;
  /** Domain returned by TonConnect's signData method. */
  domain: string;
  /** Contains text 'CANCEL <QUOTE-ID-HEX>' */
  payload: string;
  /** Base64 signature returned by TonConnect's signData method. */
  signature: string;
}

/**
 * TODO: unstable API
 * Signed cancellation of gasless order
 */
export interface GaslessCancellation {
  gaslessCancellation: GaslessCancellation_GaslessCancellationOneOf | undefined;
}

export interface GaslessCancellation_GaslessCancellationOneOf {
  ton?: TonGaslessCancellation | undefined;
}

function createBaseTonGaslessPayload(): TonGaslessPayload {
  return { cell: "", schema: "" };
}

export const TonGaslessPayload: MessageFns<TonGaslessPayload> = {
  fromJSON(object: any): TonGaslessPayload {
    return {
      cell: isSet(object.cell) ? globalThis.String(object.cell) : "",
      schema: isSet(object.schema) ? globalThis.String(object.schema) : "",
    };
  },

  toJSON(message: TonGaslessPayload): unknown {
    const obj: any = {};
    if (message.cell !== undefined) {
      obj.cell = message.cell;
    }
    if (message.schema !== undefined) {
      obj.schema = message.schema;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonGaslessPayload>, I>>(
    base?: I,
  ): TonGaslessPayload {
    return TonGaslessPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonGaslessPayload>, I>>(
    object: I,
  ): TonGaslessPayload {
    const message = createBaseTonGaslessPayload();
    message.cell = object.cell ?? "";
    message.schema = object.schema ?? "";
    return message;
  },
};

function createBaseGaslessPayload(): GaslessPayload {
  return { gaslessPayload: undefined };
}

export const GaslessPayload: MessageFns<GaslessPayload> = {
  fromJSON(object: any): GaslessPayload {
    return {
      gaslessPayload: isSet(object.gasless_payload)
        ? GaslessPayload_GaslessPayloadOneOf.fromJSON(object.gasless_payload)
        : undefined,
    };
  },

  toJSON(message: GaslessPayload): unknown {
    const obj: any = {};
    if (message.gaslessPayload !== undefined) {
      obj.gasless_payload = GaslessPayload_GaslessPayloadOneOf.toJSON(
        message.gaslessPayload,
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GaslessPayload>, I>>(
    base?: I,
  ): GaslessPayload {
    return GaslessPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GaslessPayload>, I>>(
    object: I,
  ): GaslessPayload {
    const message = createBaseGaslessPayload();
    message.gaslessPayload =
      object.gaslessPayload !== undefined && object.gaslessPayload !== null
        ? GaslessPayload_GaslessPayloadOneOf.fromPartial(object.gaslessPayload)
        : undefined;
    return message;
  },
};

function createBaseGaslessPayload_GaslessPayloadOneOf(): GaslessPayload_GaslessPayloadOneOf {
  return { ton: undefined };
}

export const GaslessPayload_GaslessPayloadOneOf: MessageFns<GaslessPayload_GaslessPayloadOneOf> =
  {
    fromJSON(object: any): GaslessPayload_GaslessPayloadOneOf {
      return {
        ton: isSet(object.ton)
          ? TonGaslessPayload.fromJSON(object.ton)
          : undefined,
      };
    },

    toJSON(message: GaslessPayload_GaslessPayloadOneOf): unknown {
      const obj: any = {};
      if (message.ton !== undefined) {
        obj.ton = TonGaslessPayload.toJSON(message.ton);
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<GaslessPayload_GaslessPayloadOneOf>, I>>(
      base?: I,
    ): GaslessPayload_GaslessPayloadOneOf {
      return GaslessPayload_GaslessPayloadOneOf.fromPartial(
        base ?? ({} as any),
      );
    },
    fromPartial<
      I extends Exact<DeepPartial<GaslessPayload_GaslessPayloadOneOf>, I>,
    >(object: I): GaslessPayload_GaslessPayloadOneOf {
      const message = createBaseGaslessPayload_GaslessPayloadOneOf();
      message.ton =
        object.ton !== undefined && object.ton !== null
          ? TonGaslessPayload.fromPartial(object.ton)
          : undefined;
      return message;
    },
  };

function createBaseTonGaslessOrder(): TonGaslessOrder {
  return {
    walletAddress: "",
    timestamp: 0,
    domain: "",
    payload: "",
    signature: "",
  };
}

export const TonGaslessOrder: MessageFns<TonGaslessOrder> = {
  fromJSON(object: any): TonGaslessOrder {
    return {
      walletAddress: isSet(object.wallet_address)
        ? globalThis.String(object.wallet_address)
        : "",
      timestamp: isSet(object.timestamp)
        ? globalThis.Number(object.timestamp)
        : 0,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
      signature: isSet(object.signature)
        ? globalThis.String(object.signature)
        : "",
    };
  },

  toJSON(message: TonGaslessOrder): unknown {
    const obj: any = {};
    if (message.walletAddress !== undefined) {
      obj.wallet_address = message.walletAddress;
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.domain !== undefined) {
      obj.domain = message.domain;
    }
    if (message.payload !== undefined) {
      obj.payload = message.payload;
    }
    if (message.signature !== undefined) {
      obj.signature = message.signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonGaslessOrder>, I>>(
    base?: I,
  ): TonGaslessOrder {
    return TonGaslessOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonGaslessOrder>, I>>(
    object: I,
  ): TonGaslessOrder {
    const message = createBaseTonGaslessOrder();
    message.walletAddress = object.walletAddress ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.domain = object.domain ?? "";
    message.payload = object.payload ?? "";
    message.signature = object.signature ?? "";
    return message;
  },
};

function createBaseGaslessOrder(): GaslessOrder {
  return { gaslessOrder: undefined };
}

export const GaslessOrder: MessageFns<GaslessOrder> = {
  fromJSON(object: any): GaslessOrder {
    return {
      gaslessOrder: isSet(object.gasless_order)
        ? GaslessOrder_GaslessOrderOneOf.fromJSON(object.gasless_order)
        : undefined,
    };
  },

  toJSON(message: GaslessOrder): unknown {
    const obj: any = {};
    if (message.gaslessOrder !== undefined) {
      obj.gasless_order = GaslessOrder_GaslessOrderOneOf.toJSON(
        message.gaslessOrder,
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GaslessOrder>, I>>(
    base?: I,
  ): GaslessOrder {
    return GaslessOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GaslessOrder>, I>>(
    object: I,
  ): GaslessOrder {
    const message = createBaseGaslessOrder();
    message.gaslessOrder =
      object.gaslessOrder !== undefined && object.gaslessOrder !== null
        ? GaslessOrder_GaslessOrderOneOf.fromPartial(object.gaslessOrder)
        : undefined;
    return message;
  },
};

function createBaseGaslessOrder_GaslessOrderOneOf(): GaslessOrder_GaslessOrderOneOf {
  return { ton: undefined };
}

export const GaslessOrder_GaslessOrderOneOf: MessageFns<GaslessOrder_GaslessOrderOneOf> =
  {
    fromJSON(object: any): GaslessOrder_GaslessOrderOneOf {
      return {
        ton: isSet(object.ton)
          ? TonGaslessOrder.fromJSON(object.ton)
          : undefined,
      };
    },

    toJSON(message: GaslessOrder_GaslessOrderOneOf): unknown {
      const obj: any = {};
      if (message.ton !== undefined) {
        obj.ton = TonGaslessOrder.toJSON(message.ton);
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<GaslessOrder_GaslessOrderOneOf>, I>>(
      base?: I,
    ): GaslessOrder_GaslessOrderOneOf {
      return GaslessOrder_GaslessOrderOneOf.fromPartial(base ?? ({} as any));
    },
    fromPartial<
      I extends Exact<DeepPartial<GaslessOrder_GaslessOrderOneOf>, I>,
    >(object: I): GaslessOrder_GaslessOrderOneOf {
      const message = createBaseGaslessOrder_GaslessOrderOneOf();
      message.ton =
        object.ton !== undefined && object.ton !== null
          ? TonGaslessOrder.fromPartial(object.ton)
          : undefined;
      return message;
    },
  };

function createBaseTonGaslessCancellation(): TonGaslessCancellation {
  return {
    walletAddress: "",
    timestamp: 0,
    domain: "",
    payload: "",
    signature: "",
  };
}

export const TonGaslessCancellation: MessageFns<TonGaslessCancellation> = {
  fromJSON(object: any): TonGaslessCancellation {
    return {
      walletAddress: isSet(object.wallet_address)
        ? globalThis.String(object.wallet_address)
        : "",
      timestamp: isSet(object.timestamp)
        ? globalThis.Number(object.timestamp)
        : 0,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
      signature: isSet(object.signature)
        ? globalThis.String(object.signature)
        : "",
    };
  },

  toJSON(message: TonGaslessCancellation): unknown {
    const obj: any = {};
    if (message.walletAddress !== undefined) {
      obj.wallet_address = message.walletAddress;
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.domain !== undefined) {
      obj.domain = message.domain;
    }
    if (message.payload !== undefined) {
      obj.payload = message.payload;
    }
    if (message.signature !== undefined) {
      obj.signature = message.signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonGaslessCancellation>, I>>(
    base?: I,
  ): TonGaslessCancellation {
    return TonGaslessCancellation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonGaslessCancellation>, I>>(
    object: I,
  ): TonGaslessCancellation {
    const message = createBaseTonGaslessCancellation();
    message.walletAddress = object.walletAddress ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.domain = object.domain ?? "";
    message.payload = object.payload ?? "";
    message.signature = object.signature ?? "";
    return message;
  },
};

function createBaseGaslessCancellation(): GaslessCancellation {
  return { gaslessCancellation: undefined };
}

export const GaslessCancellation: MessageFns<GaslessCancellation> = {
  fromJSON(object: any): GaslessCancellation {
    return {
      gaslessCancellation: isSet(object.gasless_cancellation)
        ? GaslessCancellation_GaslessCancellationOneOf.fromJSON(
            object.gasless_cancellation,
          )
        : undefined,
    };
  },

  toJSON(message: GaslessCancellation): unknown {
    const obj: any = {};
    if (message.gaslessCancellation !== undefined) {
      obj.gasless_cancellation =
        GaslessCancellation_GaslessCancellationOneOf.toJSON(
          message.gaslessCancellation,
        );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GaslessCancellation>, I>>(
    base?: I,
  ): GaslessCancellation {
    return GaslessCancellation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GaslessCancellation>, I>>(
    object: I,
  ): GaslessCancellation {
    const message = createBaseGaslessCancellation();
    message.gaslessCancellation =
      object.gaslessCancellation !== undefined &&
      object.gaslessCancellation !== null
        ? GaslessCancellation_GaslessCancellationOneOf.fromPartial(
            object.gaslessCancellation,
          )
        : undefined;
    return message;
  },
};

function createBaseGaslessCancellation_GaslessCancellationOneOf(): GaslessCancellation_GaslessCancellationOneOf {
  return { ton: undefined };
}

export const GaslessCancellation_GaslessCancellationOneOf: MessageFns<GaslessCancellation_GaslessCancellationOneOf> =
  {
    fromJSON(object: any): GaslessCancellation_GaslessCancellationOneOf {
      return {
        ton: isSet(object.ton)
          ? TonGaslessCancellation.fromJSON(object.ton)
          : undefined,
      };
    },

    toJSON(message: GaslessCancellation_GaslessCancellationOneOf): unknown {
      const obj: any = {};
      if (message.ton !== undefined) {
        obj.ton = TonGaslessCancellation.toJSON(message.ton);
      }
      return obj;
    },

    create<
      I extends Exact<
        DeepPartial<GaslessCancellation_GaslessCancellationOneOf>,
        I
      >,
    >(base?: I): GaslessCancellation_GaslessCancellationOneOf {
      return GaslessCancellation_GaslessCancellationOneOf.fromPartial(
        base ?? ({} as any),
      );
    },
    fromPartial<
      I extends Exact<
        DeepPartial<GaslessCancellation_GaslessCancellationOneOf>,
        I
      >,
    >(object: I): GaslessCancellation_GaslessCancellationOneOf {
      const message = createBaseGaslessCancellation_GaslessCancellationOneOf();
      message.ton =
        object.ton !== undefined && object.ton !== null
          ? TonGaslessCancellation.fromPartial(object.ton)
          : undefined;
      return message;
    },
  };

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
