// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/trader/order.proto

// @ts-nocheck
// oxlint-disable

import { AssetId } from "../../../common/v1/types/asset_id";
import { ChainAddress } from "../../../common/v1/types/chain_address";
import { Order, SignedOrder, SignedOrderCancellation } from "../types/order";
import { OrderSettlementParams, Quote } from "../types/quote";

/** *UNSTABLE** A request for Limit Order quote (RFQ) sent by the trader */
export interface LimitOrderCreateRequest {
  /** Blockchain-specific address of **Input asset**. */
  inputAsset: AssetId;
  /** Blockchain-specific address of **Output asset**. */
  outputAsset: AssetId;
  /**
   * The amount of **Input asset** the trader wants to exchange, including all
   * fees.
   */
  inputUnits: string;
  /** The amount of **Output asset** the trader wants to get after all fees. */
  outputUnits: string;
  /** The address of integrator that will receive the fees. */
  integratorAddress: ChainAddress;
  /**
   * The amount of fees required by the integrator in percentage in points
   * (1/1,000,000 or 0.0001%)
   */
  integratorFeePips?: number | undefined;
  /** Parameters specific to order settlement. */
  settlementParams: OrderSettlementParams;
}

/** *UNSTABLE** A request for Limit Order quote (RFQ) sent by the trader */
export interface LimitOrderResponse {
  quote: Quote;
}

/** Requests the list of currently active orders for a trader. */
export interface ActiveOrdersRequest {
  /** The address of trader's wallet that has initiated the order */
  traderAddress: ChainAddress;
}

/** Describes active Order together with the Quote. */
export interface ActiveOrder {
  order: Order;
  quote: Quote;
}

/** Response containing all currently active orders for a trader. */
export interface ActiveOrdersResponse {
  activeOrders: ActiveOrder[];
}

/** A request to track the execution of specific order */
export interface TrackOrderRequest {
  /** ID of the quote */
  quoteId: string;
  /** The address of trader's wallet that initiated transaction */
  traderAddress: ChainAddress;
}

/** Registers a signed gasless order with the protocol. */
export interface RegisterSignedOrderRequest {
  /** ID of the quote */
  quoteId: string;
  /** The address on **Source** blockchain that has signed the order. */
  ownerSrcAddress: ChainAddress;
  /** The body of the order in blockchain-specific encoding. */
  signedOrder: SignedOrder;
  /**
   * Off-chain **Order details** in protobuf-serialized form.
   *
   * This payload must contain exactly the same serialized
   * `VersionedHtlcOrderDetails` that was produced when the order payload was
   * built, and whose hash is embedded into the signed order.
   *
   * It is transferred in serialized form to avoid differences in binary
   * representation after a deserialize-serialize cycle.
   */
  serializedOrderDetails?: Uint8Array | undefined;
}

/** Requests cancellation of a previously registered signed order. */
export interface CancelSignedOrderRequest {
  /** ID of the quote corresponding to the order being cancelled. */
  quoteId: string;
  /**
   * The address on **Source** blockchain that signed the order cancellation.
   *
   * This address must match the wallet that signed the corresponding **Signed
   * Order**.
   */
  ownerSrcAddress: ChainAddress;
  /** The blockchain-specific signed cancellation payload. */
  signedCancellation: SignedOrderCancellation;
}

/** Indicates that the signed order was cancelled using the off-chain path. */
export interface SignedOrderCancelledOffchain {}

/**
 * Indicates that off-chain cancellation is insufficient and on-chain
 * cancellation is required.
 */
export interface SignedOrderOnchainCancellationRequired {
  /**
   * The current state of the order, indicating that the trader must use an
   * on-chain cancellation flow.
   */
  order: Order;
}

/** Result of attempting to cancel a signed order. */
export interface CancelSignedOrderResponse {
  result:
    //
    /**
     * The order has been successfully cancelled using the submitted off-chain
     * payload.
     */
    | {
        $case: "cancelledOffchain";
        value: SignedOrderCancelledOffchain;
      } //
    /**
     * Off-chain cancellation is not sufficient and the order requires an
     * on-chain cancellation flow.
     */
    | {
        $case: "requiresOnchain";
        value: SignedOrderOnchainCancellationRequired;
      };
}

/**
 * Discloses the HTLC secret for a specific execution, allowing the
 * **Output position** on **Destination blockchain** to be claimed or redeemed.
 */
export interface DiscloseHtlcSecretRequest {
  quoteId: string;
  /**
   * Index of the execution, used for tracking partial fills.
   *
   * This parameter should contain 0 for single-execution trades.
   */
  executionIndex: number;
  /**
   * The 256-bit value of the secret that should be used to redeem the **Output
   * position**.
   */
  secret: Uint8Array;
}

function createBaseLimitOrderCreateRequest(): LimitOrderCreateRequest {
  return {
    inputAsset: undefined,
    outputAsset: undefined,
    inputUnits: "",
    outputUnits: "",
    integratorAddress: undefined,
    integratorFeePips: undefined,
    settlementParams: undefined,
  };
}

export const LimitOrderCreateRequest: MessageFns<LimitOrderCreateRequest> = {
  fromJSON(object: any): LimitOrderCreateRequest {
    return {
      inputAsset: isSet(object.input_asset) ? AssetId.fromJSON(object.input_asset) : undefined,
      outputAsset: isSet(object.output_asset) ? AssetId.fromJSON(object.output_asset) : undefined,
      inputUnits: isSet(object.input_units) ? globalThis.String(object.input_units) : "",
      outputUnits: isSet(object.output_units) ? globalThis.String(object.output_units) : "",
      integratorAddress: isSet(object.integrator_address)
        ? ChainAddress.fromJSON(object.integrator_address)
        : undefined,
      integratorFeePips: isSet(object.integrator_fee_pips)
        ? globalThis.Number(object.integrator_fee_pips)
        : undefined,
      settlementParams: isSet(object.settlement_params)
        ? OrderSettlementParams.fromJSON(object.settlement_params)
        : undefined,
    };
  },

  toJSON(message: LimitOrderCreateRequest): unknown {
    const obj: any = {};
    if (message.inputAsset !== undefined) {
      obj.input_asset = AssetId.toJSON(message.inputAsset);
    }
    if (message.outputAsset !== undefined) {
      obj.output_asset = AssetId.toJSON(message.outputAsset);
    }
    if (message.inputUnits !== undefined) {
      obj.input_units = message.inputUnits;
    }
    if (message.outputUnits !== undefined) {
      obj.output_units = message.outputUnits;
    }
    if (message.integratorAddress !== undefined) {
      obj.integrator_address = ChainAddress.toJSON(message.integratorAddress);
    }
    if (message.integratorFeePips !== undefined) {
      obj.integrator_fee_pips = Math.round(message.integratorFeePips);
    }
    if (message.settlementParams !== undefined) {
      obj.settlement_params = OrderSettlementParams.toJSON(message.settlementParams);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LimitOrderCreateRequest>, I>>(
    base?: I,
  ): LimitOrderCreateRequest {
    return LimitOrderCreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LimitOrderCreateRequest>, I>>(
    object: I,
  ): LimitOrderCreateRequest {
    const message = createBaseLimitOrderCreateRequest();
    message.inputAsset =
      object.inputAsset !== undefined && object.inputAsset !== null
        ? AssetId.fromPartial(object.inputAsset)
        : undefined;
    message.outputAsset =
      object.outputAsset !== undefined && object.outputAsset !== null
        ? AssetId.fromPartial(object.outputAsset)
        : undefined;
    message.inputUnits = object.inputUnits ?? "";
    message.outputUnits = object.outputUnits ?? "";
    message.integratorAddress =
      object.integratorAddress !== undefined && object.integratorAddress !== null
        ? ChainAddress.fromPartial(object.integratorAddress)
        : undefined;
    message.integratorFeePips = object.integratorFeePips ?? undefined;
    message.settlementParams =
      object.settlementParams !== undefined && object.settlementParams !== null
        ? OrderSettlementParams.fromPartial(object.settlementParams)
        : undefined;
    return message;
  },
};

function createBaseLimitOrderResponse(): LimitOrderResponse {
  return { quote: undefined };
}

export const LimitOrderResponse: MessageFns<LimitOrderResponse> = {
  fromJSON(object: any): LimitOrderResponse {
    return { quote: isSet(object.quote) ? Quote.fromJSON(object.quote) : undefined };
  },

  toJSON(message: LimitOrderResponse): unknown {
    const obj: any = {};
    if (message.quote !== undefined) {
      obj.quote = Quote.toJSON(message.quote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LimitOrderResponse>, I>>(base?: I): LimitOrderResponse {
    return LimitOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LimitOrderResponse>, I>>(object: I): LimitOrderResponse {
    const message = createBaseLimitOrderResponse();
    message.quote =
      object.quote !== undefined && object.quote !== null
        ? Quote.fromPartial(object.quote)
        : undefined;
    return message;
  },
};

function createBaseActiveOrdersRequest(): ActiveOrdersRequest {
  return { traderAddress: undefined };
}

export const ActiveOrdersRequest: MessageFns<ActiveOrdersRequest> = {
  fromJSON(object: any): ActiveOrdersRequest {
    return {
      traderAddress: isSet(object.trader_address)
        ? ChainAddress.fromJSON(object.trader_address)
        : undefined,
    };
  },

  toJSON(message: ActiveOrdersRequest): unknown {
    const obj: any = {};
    if (message.traderAddress !== undefined) {
      obj.trader_address = ChainAddress.toJSON(message.traderAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActiveOrdersRequest>, I>>(base?: I): ActiveOrdersRequest {
    return ActiveOrdersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActiveOrdersRequest>, I>>(
    object: I,
  ): ActiveOrdersRequest {
    const message = createBaseActiveOrdersRequest();
    message.traderAddress =
      object.traderAddress !== undefined && object.traderAddress !== null
        ? ChainAddress.fromPartial(object.traderAddress)
        : undefined;
    return message;
  },
};

function createBaseActiveOrder(): ActiveOrder {
  return { order: undefined, quote: undefined };
}

export const ActiveOrder: MessageFns<ActiveOrder> = {
  fromJSON(object: any): ActiveOrder {
    return {
      order: isSet(object.order) ? Order.fromJSON(object.order) : undefined,
      quote: isSet(object.quote) ? Quote.fromJSON(object.quote) : undefined,
    };
  },

  toJSON(message: ActiveOrder): unknown {
    const obj: any = {};
    if (message.order !== undefined) {
      obj.order = Order.toJSON(message.order);
    }
    if (message.quote !== undefined) {
      obj.quote = Quote.toJSON(message.quote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActiveOrder>, I>>(base?: I): ActiveOrder {
    return ActiveOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActiveOrder>, I>>(object: I): ActiveOrder {
    const message = createBaseActiveOrder();
    message.order =
      object.order !== undefined && object.order !== null
        ? Order.fromPartial(object.order)
        : undefined;
    message.quote =
      object.quote !== undefined && object.quote !== null
        ? Quote.fromPartial(object.quote)
        : undefined;
    return message;
  },
};

function createBaseActiveOrdersResponse(): ActiveOrdersResponse {
  return { activeOrders: [] };
}

export const ActiveOrdersResponse: MessageFns<ActiveOrdersResponse> = {
  fromJSON(object: any): ActiveOrdersResponse {
    return {
      activeOrders: globalThis.Array.isArray(object?.active_orders)
        ? object.active_orders.map((e: any) => ActiveOrder.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ActiveOrdersResponse): unknown {
    const obj: any = {};
    if (message.activeOrders?.length) {
      obj.active_orders = message.activeOrders.map((e) => ActiveOrder.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActiveOrdersResponse>, I>>(base?: I): ActiveOrdersResponse {
    return ActiveOrdersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActiveOrdersResponse>, I>>(
    object: I,
  ): ActiveOrdersResponse {
    const message = createBaseActiveOrdersResponse();
    message.activeOrders = object.activeOrders?.map((e) => ActiveOrder.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTrackOrderRequest(): TrackOrderRequest {
  return { quoteId: "", traderAddress: undefined };
}

export const TrackOrderRequest: MessageFns<TrackOrderRequest> = {
  fromJSON(object: any): TrackOrderRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      traderAddress: isSet(object.trader_address)
        ? ChainAddress.fromJSON(object.trader_address)
        : undefined,
    };
  },

  toJSON(message: TrackOrderRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.traderAddress !== undefined) {
      obj.trader_address = ChainAddress.toJSON(message.traderAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrackOrderRequest>, I>>(base?: I): TrackOrderRequest {
    return TrackOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrackOrderRequest>, I>>(object: I): TrackOrderRequest {
    const message = createBaseTrackOrderRequest();
    message.quoteId = object.quoteId ?? "";
    message.traderAddress =
      object.traderAddress !== undefined && object.traderAddress !== null
        ? ChainAddress.fromPartial(object.traderAddress)
        : undefined;
    return message;
  },
};

function createBaseRegisterSignedOrderRequest(): RegisterSignedOrderRequest {
  return {
    quoteId: "",
    ownerSrcAddress: undefined,
    signedOrder: undefined,
    serializedOrderDetails: undefined,
  };
}

export const RegisterSignedOrderRequest: MessageFns<RegisterSignedOrderRequest> = {
  fromJSON(object: any): RegisterSignedOrderRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      ownerSrcAddress: isSet(object.owner_src_address)
        ? ChainAddress.fromJSON(object.owner_src_address)
        : undefined,
      signedOrder: isSet(object.signed_order)
        ? SignedOrder.fromJSON(object.signed_order)
        : undefined,
      serializedOrderDetails: isSet(object.serialized_order_details)
        ? bytesFromBase64(object.serialized_order_details)
        : undefined,
    };
  },

  toJSON(message: RegisterSignedOrderRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.ownerSrcAddress !== undefined) {
      obj.owner_src_address = ChainAddress.toJSON(message.ownerSrcAddress);
    }
    if (message.signedOrder !== undefined) {
      obj.signed_order = SignedOrder.toJSON(message.signedOrder);
    }
    if (message.serializedOrderDetails !== undefined) {
      obj.serialized_order_details = base64FromBytes(message.serializedOrderDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterSignedOrderRequest>, I>>(
    base?: I,
  ): RegisterSignedOrderRequest {
    return RegisterSignedOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterSignedOrderRequest>, I>>(
    object: I,
  ): RegisterSignedOrderRequest {
    const message = createBaseRegisterSignedOrderRequest();
    message.quoteId = object.quoteId ?? "";
    message.ownerSrcAddress =
      object.ownerSrcAddress !== undefined && object.ownerSrcAddress !== null
        ? ChainAddress.fromPartial(object.ownerSrcAddress)
        : undefined;
    message.signedOrder =
      object.signedOrder !== undefined && object.signedOrder !== null
        ? SignedOrder.fromPartial(object.signedOrder)
        : undefined;
    message.serializedOrderDetails = object.serializedOrderDetails ?? undefined;
    return message;
  },
};

function createBaseCancelSignedOrderRequest(): CancelSignedOrderRequest {
  return { quoteId: "", ownerSrcAddress: undefined, signedCancellation: undefined };
}

export const CancelSignedOrderRequest: MessageFns<CancelSignedOrderRequest> = {
  fromJSON(object: any): CancelSignedOrderRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      ownerSrcAddress: isSet(object.owner_src_address)
        ? ChainAddress.fromJSON(object.owner_src_address)
        : undefined,
      signedCancellation: isSet(object.signed_cancellation)
        ? SignedOrderCancellation.fromJSON(object.signed_cancellation)
        : undefined,
    };
  },

  toJSON(message: CancelSignedOrderRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.ownerSrcAddress !== undefined) {
      obj.owner_src_address = ChainAddress.toJSON(message.ownerSrcAddress);
    }
    if (message.signedCancellation !== undefined) {
      obj.signed_cancellation = SignedOrderCancellation.toJSON(message.signedCancellation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelSignedOrderRequest>, I>>(
    base?: I,
  ): CancelSignedOrderRequest {
    return CancelSignedOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelSignedOrderRequest>, I>>(
    object: I,
  ): CancelSignedOrderRequest {
    const message = createBaseCancelSignedOrderRequest();
    message.quoteId = object.quoteId ?? "";
    message.ownerSrcAddress =
      object.ownerSrcAddress !== undefined && object.ownerSrcAddress !== null
        ? ChainAddress.fromPartial(object.ownerSrcAddress)
        : undefined;
    message.signedCancellation =
      object.signedCancellation !== undefined && object.signedCancellation !== null
        ? SignedOrderCancellation.fromPartial(object.signedCancellation)
        : undefined;
    return message;
  },
};

function createBaseSignedOrderCancelledOffchain(): SignedOrderCancelledOffchain {
  return {};
}

export const SignedOrderCancelledOffchain: MessageFns<SignedOrderCancelledOffchain> = {
  fromJSON(_: any): SignedOrderCancelledOffchain {
    return {};
  },

  toJSON(_: SignedOrderCancelledOffchain): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SignedOrderCancelledOffchain>, I>>(
    base?: I,
  ): SignedOrderCancelledOffchain {
    return SignedOrderCancelledOffchain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedOrderCancelledOffchain>, I>>(
    _: I,
  ): SignedOrderCancelledOffchain {
    const message = createBaseSignedOrderCancelledOffchain();
    return message;
  },
};

function createBaseSignedOrderOnchainCancellationRequired(): SignedOrderOnchainCancellationRequired {
  return { order: undefined };
}

export const SignedOrderOnchainCancellationRequired: MessageFns<SignedOrderOnchainCancellationRequired> =
  {
    fromJSON(object: any): SignedOrderOnchainCancellationRequired {
      return { order: isSet(object.order) ? Order.fromJSON(object.order) : undefined };
    },

    toJSON(message: SignedOrderOnchainCancellationRequired): unknown {
      const obj: any = {};
      if (message.order !== undefined) {
        obj.order = Order.toJSON(message.order);
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<SignedOrderOnchainCancellationRequired>, I>>(
      base?: I,
    ): SignedOrderOnchainCancellationRequired {
      return SignedOrderOnchainCancellationRequired.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<SignedOrderOnchainCancellationRequired>, I>>(
      object: I,
    ): SignedOrderOnchainCancellationRequired {
      const message = createBaseSignedOrderOnchainCancellationRequired();
      message.order =
        object.order !== undefined && object.order !== null
          ? Order.fromPartial(object.order)
          : undefined;
      return message;
    },
  };

function createBaseCancelSignedOrderResponse(): CancelSignedOrderResponse {
  return { result: undefined };
}

export const CancelSignedOrderResponse: MessageFns<CancelSignedOrderResponse> = {
  fromJSON(object: any): CancelSignedOrderResponse {
    return {
      result: isSet(object.cancelled_offchain)
        ? {
            $case: "cancelledOffchain",
            value: SignedOrderCancelledOffchain.fromJSON(object.cancelled_offchain),
          }
        : isSet(object.requires_onchain)
          ? {
              $case: "requiresOnchain",
              value: SignedOrderOnchainCancellationRequired.fromJSON(object.requires_onchain),
            }
          : undefined,
    };
  },

  toJSON(message: CancelSignedOrderResponse): unknown {
    const obj: any = {};
    if (message.result?.$case === "cancelledOffchain") {
      obj.cancelled_offchain = SignedOrderCancelledOffchain.toJSON(message.result.value);
    } else if (message.result?.$case === "requiresOnchain") {
      obj.requires_onchain = SignedOrderOnchainCancellationRequired.toJSON(message.result.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelSignedOrderResponse>, I>>(
    base?: I,
  ): CancelSignedOrderResponse {
    return CancelSignedOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelSignedOrderResponse>, I>>(
    object: I,
  ): CancelSignedOrderResponse {
    const message = createBaseCancelSignedOrderResponse();
    switch (object.result?.$case) {
      case "cancelledOffchain": {
        if (object.result?.value !== undefined && object.result?.value !== null) {
          message.result = {
            $case: "cancelledOffchain",
            value: SignedOrderCancelledOffchain.fromPartial(object.result.value),
          };
        }
        break;
      }
      case "requiresOnchain": {
        if (object.result?.value !== undefined && object.result?.value !== null) {
          message.result = {
            $case: "requiresOnchain",
            value: SignedOrderOnchainCancellationRequired.fromPartial(object.result.value),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseDiscloseHtlcSecretRequest(): DiscloseHtlcSecretRequest {
  return { quoteId: "", executionIndex: 0, secret: new Uint8Array(0) };
}

export const DiscloseHtlcSecretRequest: MessageFns<DiscloseHtlcSecretRequest> = {
  fromJSON(object: any): DiscloseHtlcSecretRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      executionIndex: isSet(object.execution_index) ? globalThis.Number(object.execution_index) : 0,
      secret: isSet(object.secret) ? bytesFromBase64(object.secret) : new Uint8Array(0),
    };
  },

  toJSON(message: DiscloseHtlcSecretRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.executionIndex !== undefined) {
      obj.execution_index = Math.round(message.executionIndex);
    }
    if (message.secret !== undefined) {
      obj.secret = base64FromBytes(message.secret);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiscloseHtlcSecretRequest>, I>>(
    base?: I,
  ): DiscloseHtlcSecretRequest {
    return DiscloseHtlcSecretRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiscloseHtlcSecretRequest>, I>>(
    object: I,
  ): DiscloseHtlcSecretRequest {
    const message = createBaseDiscloseHtlcSecretRequest();
    message.quoteId = object.quoteId ?? "";
    message.executionIndex = object.executionIndex ?? 0;
    message.secret = object.secret ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
