// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/trader/quote.proto

// @ts-nocheck
// oxlint-disable

import { KeepAlive } from "../types/common";
import { Quote } from "../types/quote";

/** Indicates that the's no valid quote corresponding to RFQ. */
export interface NoQuoteEvent {}

/**
 * Server sends acknowledge immediately upon reception of QuoteRequest and
 * generation of `rfq_id`.
 */
export interface QuoteRequestAck {
  /** ID of RFQ generated by the server (SHA-256 hex string). */
  rfqId: string;
}

/** One event in the quote stream returned for an RFQ. */
export interface QuoteEvent {
  event:
    //
    /**
     * Server sends acknowledge immediately upon reception of QuoteRequest and
     * generation of `rfq_id`.
     */
    | {
        $case: "ack";
        value: QuoteRequestAck;
      } //
    /**
     * Represents an updated quote received from the server in response to a
     * quote request.
     */
    | {
        $case: "quoteUpdated";
        value: Quote;
      } //
    /** Indicates that the's no valid quote corresponding to RFQ. */
    | {
        $case: "noQuote";
        value: NoQuoteEvent;
      } //
    /** The service message to keep connection alive. */
    | {
        $case: "keepAlive";
        value: KeepAlive;
      };
}

function createBaseNoQuoteEvent(): NoQuoteEvent {
  return {};
}

export const NoQuoteEvent: MessageFns<NoQuoteEvent> = {
  fromJSON(_: any): NoQuoteEvent {
    return {};
  },

  toJSON(_: NoQuoteEvent): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<NoQuoteEvent>, I>>(base?: I): NoQuoteEvent {
    return NoQuoteEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NoQuoteEvent>, I>>(_: I): NoQuoteEvent {
    const message = createBaseNoQuoteEvent();
    return message;
  },
};

function createBaseQuoteRequestAck(): QuoteRequestAck {
  return { rfqId: "" };
}

export const QuoteRequestAck: MessageFns<QuoteRequestAck> = {
  fromJSON(object: any): QuoteRequestAck {
    return { rfqId: isSet(object.rfq_id) ? globalThis.String(object.rfq_id) : "" };
  },

  toJSON(message: QuoteRequestAck): unknown {
    const obj: any = {};
    if (message.rfqId !== undefined) {
      obj.rfq_id = message.rfqId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuoteRequestAck>, I>>(base?: I): QuoteRequestAck {
    return QuoteRequestAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuoteRequestAck>, I>>(object: I): QuoteRequestAck {
    const message = createBaseQuoteRequestAck();
    message.rfqId = object.rfqId ?? "";
    return message;
  },
};

function createBaseQuoteEvent(): QuoteEvent {
  return { event: undefined };
}

export const QuoteEvent: MessageFns<QuoteEvent> = {
  fromJSON(object: any): QuoteEvent {
    return {
      event: isSet(object.ack)
        ? { $case: "ack", value: QuoteRequestAck.fromJSON(object.ack) }
        : isSet(object.quote_updated)
          ? { $case: "quoteUpdated", value: Quote.fromJSON(object.quote_updated) }
          : isSet(object.no_quote)
            ? { $case: "noQuote", value: NoQuoteEvent.fromJSON(object.no_quote) }
            : isSet(object.keep_alive)
              ? { $case: "keepAlive", value: KeepAlive.fromJSON(object.keep_alive) }
              : undefined,
    };
  },

  toJSON(message: QuoteEvent): unknown {
    const obj: any = {};
    if (message.event?.$case === "ack") {
      obj.ack = QuoteRequestAck.toJSON(message.event.value);
    } else if (message.event?.$case === "quoteUpdated") {
      obj.quote_updated = Quote.toJSON(message.event.value);
    } else if (message.event?.$case === "noQuote") {
      obj.no_quote = NoQuoteEvent.toJSON(message.event.value);
    } else if (message.event?.$case === "keepAlive") {
      obj.keep_alive = KeepAlive.toJSON(message.event.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuoteEvent>, I>>(base?: I): QuoteEvent {
    return QuoteEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuoteEvent>, I>>(object: I): QuoteEvent {
    const message = createBaseQuoteEvent();
    switch (object.event?.$case) {
      case "ack": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = { $case: "ack", value: QuoteRequestAck.fromPartial(object.event.value) };
        }
        break;
      }
      case "quoteUpdated": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = { $case: "quoteUpdated", value: Quote.fromPartial(object.event.value) };
        }
        break;
      }
      case "noQuote": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = { $case: "noQuote", value: NoQuoteEvent.fromPartial(object.event.value) };
        }
        break;
      }
      case "keepAlive": {
        if (object.event?.value !== undefined && object.event?.value !== null) {
          message.event = { $case: "keepAlive", value: KeepAlive.fromPartial(object.event.value) };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
