// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/common/v1/types/asset_id.proto

// @ts-nocheck
// oxlint-disable

import { Empty } from "../../../../google/protobuf/empty";

/** Generic blockchain asset identifier */
export interface AssetId {
  /**
   * ////////////////////////////////////////////////
   * EVM
   * ////////////////////////////////////////////////
   */
  chain:
    //
    /** Arbitrum (see [https://arbitrum.io/]) */
    | {
        $case: "arbitrum";
        value: EvmAssetId;
      } //
    /** Avalanche C-Chain (see [https://www.avax.network/]) */
    | {
        $case: "avalanche";
        value: EvmAssetId;
      } //
    /** Base (see [https://www.base.org/]) */
    | {
        $case: "base";
        value: EvmAssetId;
      } //
    /** BNB Chain (see [https://www.bnbchain.org/]) */
    | {
        $case: "bnb";
        value: EvmAssetId;
      } //
    /** Ethereum (see [https://ethereum.org/]) */
    | {
        $case: "ethereum";
        value: EvmAssetId;
      } //
    /** Polygon (see [https://polygon.technology/]) */
    | {
        $case: "polygon";
        value: EvmAssetId;
      } //
    /** TON (see [https://ton.org]) */
    | {
        $case: "ton";
        value: TonAssetId;
      };
}

/** TON asset id (see [https://ton.org]) */
export interface TonAssetId {
  kind:
    //
    /** Toncoin */
    | {
        $case: "native";
        value: Empty;
      } //
    /**
     * Jetton contract address (see
     * [https://github.com/ton-blockchain/TEPs/blob/master/text/0074-jettons-standard.md])
     * in any valid TON string format (see
     * [https://docs.ton.org/foundations/addresses/formats]).
     */
    | {
        $case: "jetton";
        value: string;
      };
}

/** EVM asset id (see [https://ethereum.org/developers/docs/evm/]) */
export interface EvmAssetId {
  kind:
    //
    /** Native EVM asset */
    | {
        $case: "native";
        value: Empty;
      } //
    /**
     * ERC-20 contract address (see
     * [https://ethereum.org/developers/docs/standards/tokens/erc-20/])
     * in valid EIP-55 string format (see
     * [https://eips.ethereum.org/EIPS/eip-55])
     */
    | {
        $case: "erc20";
        value: string;
      } //
    /** ERC-1155 asset (see [https://eips.ethereum.org/EIPS/eip-1155]) */
    | {
        $case: "erc1155";
        value: Erc1155AssetId;
      };
}

/** ERC-1155 asset id (see [https://eips.ethereum.org/EIPS/eip-1155]) */
export interface Erc1155AssetId {
  /**
   * ERC-1155 contract address in valid EIP-55 string format (see
   * [https://eips.ethereum.org/EIPS/eip-55])
   */
  contractAddress: string;
  /**
   * Token ID (uint256)
   * Supports: Decimal ("42"), Hex ("0x2A"), Octal ("0o52"), or Binary
   * ("0b101010").
   */
  tokenId: string;
}

function createBaseAssetId(): AssetId {
  return { chain: undefined };
}

export const AssetId: MessageFns<AssetId> = {
  fromJSON(object: any): AssetId {
    return {
      chain: isSet(object.arbitrum)
        ? { $case: "arbitrum", value: EvmAssetId.fromJSON(object.arbitrum) }
        : isSet(object.avalanche)
          ? { $case: "avalanche", value: EvmAssetId.fromJSON(object.avalanche) }
          : isSet(object.base)
            ? { $case: "base", value: EvmAssetId.fromJSON(object.base) }
            : isSet(object.bnb)
              ? { $case: "bnb", value: EvmAssetId.fromJSON(object.bnb) }
              : isSet(object.ethereum)
                ? { $case: "ethereum", value: EvmAssetId.fromJSON(object.ethereum) }
                : isSet(object.polygon)
                  ? { $case: "polygon", value: EvmAssetId.fromJSON(object.polygon) }
                  : isSet(object.ton)
                    ? { $case: "ton", value: TonAssetId.fromJSON(object.ton) }
                    : undefined,
    };
  },

  toJSON(message: AssetId): unknown {
    const obj: any = {};
    if (message.chain?.$case === "arbitrum") {
      obj.arbitrum = EvmAssetId.toJSON(message.chain.value);
    } else if (message.chain?.$case === "avalanche") {
      obj.avalanche = EvmAssetId.toJSON(message.chain.value);
    } else if (message.chain?.$case === "base") {
      obj.base = EvmAssetId.toJSON(message.chain.value);
    } else if (message.chain?.$case === "bnb") {
      obj.bnb = EvmAssetId.toJSON(message.chain.value);
    } else if (message.chain?.$case === "ethereum") {
      obj.ethereum = EvmAssetId.toJSON(message.chain.value);
    } else if (message.chain?.$case === "polygon") {
      obj.polygon = EvmAssetId.toJSON(message.chain.value);
    } else if (message.chain?.$case === "ton") {
      obj.ton = TonAssetId.toJSON(message.chain.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetId>, I>>(base?: I): AssetId {
    return AssetId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetId>, I>>(object: I): AssetId {
    const message = createBaseAssetId();
    switch (object.chain?.$case) {
      case "arbitrum": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "arbitrum", value: EvmAssetId.fromPartial(object.chain.value) };
        }
        break;
      }
      case "avalanche": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "avalanche", value: EvmAssetId.fromPartial(object.chain.value) };
        }
        break;
      }
      case "base": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "base", value: EvmAssetId.fromPartial(object.chain.value) };
        }
        break;
      }
      case "bnb": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "bnb", value: EvmAssetId.fromPartial(object.chain.value) };
        }
        break;
      }
      case "ethereum": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "ethereum", value: EvmAssetId.fromPartial(object.chain.value) };
        }
        break;
      }
      case "polygon": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "polygon", value: EvmAssetId.fromPartial(object.chain.value) };
        }
        break;
      }
      case "ton": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "ton", value: TonAssetId.fromPartial(object.chain.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseTonAssetId(): TonAssetId {
  return { kind: undefined };
}

export const TonAssetId: MessageFns<TonAssetId> = {
  fromJSON(object: any): TonAssetId {
    return {
      kind: isSet(object.native)
        ? { $case: "native", value: Empty.fromJSON(object.native) }
        : isSet(object.jetton)
          ? { $case: "jetton", value: globalThis.String(object.jetton) }
          : undefined,
    };
  },

  toJSON(message: TonAssetId): unknown {
    const obj: any = {};
    if (message.kind?.$case === "native") {
      obj.native = Empty.toJSON(message.kind.value);
    } else if (message.kind?.$case === "jetton") {
      obj.jetton = message.kind.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonAssetId>, I>>(base?: I): TonAssetId {
    return TonAssetId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonAssetId>, I>>(object: I): TonAssetId {
    const message = createBaseTonAssetId();
    switch (object.kind?.$case) {
      case "native": {
        if (object.kind?.value !== undefined && object.kind?.value !== null) {
          message.kind = { $case: "native", value: Empty.fromPartial(object.kind.value) };
        }
        break;
      }
      case "jetton": {
        if (object.kind?.value !== undefined && object.kind?.value !== null) {
          message.kind = { $case: "jetton", value: object.kind.value };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseEvmAssetId(): EvmAssetId {
  return { kind: undefined };
}

export const EvmAssetId: MessageFns<EvmAssetId> = {
  fromJSON(object: any): EvmAssetId {
    return {
      kind: isSet(object.native)
        ? { $case: "native", value: Empty.fromJSON(object.native) }
        : isSet(object.erc20)
          ? { $case: "erc20", value: globalThis.String(object.erc20) }
          : isSet(object.erc1155)
            ? { $case: "erc1155", value: Erc1155AssetId.fromJSON(object.erc1155) }
            : undefined,
    };
  },

  toJSON(message: EvmAssetId): unknown {
    const obj: any = {};
    if (message.kind?.$case === "native") {
      obj.native = Empty.toJSON(message.kind.value);
    } else if (message.kind?.$case === "erc20") {
      obj.erc20 = message.kind.value;
    } else if (message.kind?.$case === "erc1155") {
      obj.erc1155 = Erc1155AssetId.toJSON(message.kind.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EvmAssetId>, I>>(base?: I): EvmAssetId {
    return EvmAssetId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EvmAssetId>, I>>(object: I): EvmAssetId {
    const message = createBaseEvmAssetId();
    switch (object.kind?.$case) {
      case "native": {
        if (object.kind?.value !== undefined && object.kind?.value !== null) {
          message.kind = { $case: "native", value: Empty.fromPartial(object.kind.value) };
        }
        break;
      }
      case "erc20": {
        if (object.kind?.value !== undefined && object.kind?.value !== null) {
          message.kind = { $case: "erc20", value: object.kind.value };
        }
        break;
      }
      case "erc1155": {
        if (object.kind?.value !== undefined && object.kind?.value !== null) {
          message.kind = { $case: "erc1155", value: Erc1155AssetId.fromPartial(object.kind.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseErc1155AssetId(): Erc1155AssetId {
  return { contractAddress: "", tokenId: "" };
}

export const Erc1155AssetId: MessageFns<Erc1155AssetId> = {
  fromJSON(object: any): Erc1155AssetId {
    return {
      contractAddress: isSet(object.contract_address)
        ? globalThis.String(object.contract_address)
        : "",
      tokenId: isSet(object.token_id) ? globalThis.String(object.token_id) : "",
    };
  },

  toJSON(message: Erc1155AssetId): unknown {
    const obj: any = {};
    if (message.contractAddress !== undefined) {
      obj.contract_address = message.contractAddress;
    }
    if (message.tokenId !== undefined) {
      obj.token_id = message.tokenId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Erc1155AssetId>, I>>(base?: I): Erc1155AssetId {
    return Erc1155AssetId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Erc1155AssetId>, I>>(object: I): Erc1155AssetId {
    const message = createBaseErc1155AssetId();
    message.contractAddress = object.contractAddress ?? "";
    message.tokenId = object.tokenId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
