// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/common/v1/types/chain_address.proto

// @ts-nocheck
// oxlint-disable

/** Generic blockchain address */
export interface ChainAddress {
  /**
   * ////////////////////////////////////////////////
   * EVM
   * ////////////////////////////////////////////////
   */
  chain:
    //
    /**
     * Arbitrum address in valid EIP-55 string format (see
     * [https://eips.ethereum.org/EIPS/eip-55])
     */
    | {
        $case: "arbitrum";
        value: string;
      } //
    /**
     * Avalanche C-Chain address in valid EIP-55 string format (see
     * [https://eips.ethereum.org/EIPS/eip-55])
     */
    | {
        $case: "avalanche";
        value: string;
      } //
    /**
     * Base address in valid EIP-55 string format (see
     * [https://eips.ethereum.org/EIPS/eip-55])
     */
    | {
        $case: "base";
        value: string;
      } //
    /**
     * BNB Chain address in valid EIP-55 string format (see
     * [https://eips.ethereum.org/EIPS/eip-55])
     */
    | {
        $case: "bnb";
        value: string;
      } //
    /**
     * Ethereum address in valid EIP-55 string format (see
     * [https://eips.ethereum.org/EIPS/eip-55])
     */
    | {
        $case: "ethereum";
        value: string;
      } //
    /**
     * Polygon address in valid EIP-55 string format (see
     * [https://eips.ethereum.org/EIPS/eip-55])
     */
    | {
        $case: "polygon";
        value: string;
      } //
    /**
     * Any valid TON address string format (see
     * [https://docs.ton.org/foundations/addresses/formats]).
     */
    | {
        $case: "ton";
        value: string;
      };
}

function createBaseChainAddress(): ChainAddress {
  return { chain: undefined };
}

export const ChainAddress: MessageFns<ChainAddress> = {
  fromJSON(object: any): ChainAddress {
    return {
      chain: isSet(object.arbitrum)
        ? { $case: "arbitrum", value: globalThis.String(object.arbitrum) }
        : isSet(object.avalanche)
          ? { $case: "avalanche", value: globalThis.String(object.avalanche) }
          : isSet(object.base)
            ? { $case: "base", value: globalThis.String(object.base) }
            : isSet(object.bnb)
              ? { $case: "bnb", value: globalThis.String(object.bnb) }
              : isSet(object.ethereum)
                ? { $case: "ethereum", value: globalThis.String(object.ethereum) }
                : isSet(object.polygon)
                  ? { $case: "polygon", value: globalThis.String(object.polygon) }
                  : isSet(object.ton)
                    ? { $case: "ton", value: globalThis.String(object.ton) }
                    : undefined,
    };
  },

  toJSON(message: ChainAddress): unknown {
    const obj: any = {};
    if (message.chain?.$case === "arbitrum") {
      obj.arbitrum = message.chain.value;
    } else if (message.chain?.$case === "avalanche") {
      obj.avalanche = message.chain.value;
    } else if (message.chain?.$case === "base") {
      obj.base = message.chain.value;
    } else if (message.chain?.$case === "bnb") {
      obj.bnb = message.chain.value;
    } else if (message.chain?.$case === "ethereum") {
      obj.ethereum = message.chain.value;
    } else if (message.chain?.$case === "polygon") {
      obj.polygon = message.chain.value;
    } else if (message.chain?.$case === "ton") {
      obj.ton = message.chain.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChainAddress>, I>>(base?: I): ChainAddress {
    return ChainAddress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChainAddress>, I>>(object: I): ChainAddress {
    const message = createBaseChainAddress();
    switch (object.chain?.$case) {
      case "arbitrum": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "arbitrum", value: object.chain.value };
        }
        break;
      }
      case "avalanche": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "avalanche", value: object.chain.value };
        }
        break;
      }
      case "base": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "base", value: object.chain.value };
        }
        break;
      }
      case "bnb": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "bnb", value: object.chain.value };
        }
        break;
      }
      case "ethereum": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "ethereum", value: object.chain.value };
        }
        break;
      }
      case "polygon": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "polygon", value: object.chain.value };
        }
        break;
      }
      case "ton": {
        if (object.chain?.value !== undefined && object.chain?.value !== null) {
          message.chain = { $case: "ton", value: object.chain.value };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
