// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/trader/chains/evm.proto

// @ts-nocheck
// oxlint-disable

import { ChainAddress } from "../../../../common/v1/types/chain_address";
import { HtlcSecrets } from "../../types/htlc";

/** Input parameters for building an unsigned EVM signed-order payload. */
export interface BuildEvmOrderPayloadRequest {
  quoteId: string;
  /**
   * The address on **Source** blockchain that will own created position, can
   * withdraw tokens and will receive withdrawn tokens.
   */
  ownerSrcAddress: ChainAddress;
  /**
   * The address on **Destination** blockchain that will receive result of the
   * trade
   */
  traderDstAddress?: ChainAddress | undefined;
  /**
   * (HTLC-only) Allows to specify how the secrets for a multi-chunk HTLC
   * position should be defined.
   *
   * This parameter should be omitted for intrachain swaps
   */
  htlcSecrets?: HtlcSecrets | undefined;
  /**
   * (HTLC-only) The address on **Destination blockchain** that can disclose the
   * secret to claim the **Output position**.
   *
   * This address should be omitted when using public disclosure of the secret.
   */
  traderDstDiscloseAddress?: ChainAddress | undefined;
}

/** Unsigned EVM order payload and companion data required for registration. */
export interface EvmOrderPayloadResponse {
  /**
   * Json structure that contains TypedData param for signing with
   * `eth_signTypedData` as specified by EIP-712.
   *
   * This message includes at least required `types`, `primaryType`, `domain`
   * and `message` fields.
   */
  typedData: string;
  /**
   * Encoded extension data of the order.
   *
   * This data should be used when registering Intent.
   */
  orderExtension: Uint8Array;
  /**
   * Off-chain **Order details** in protobuf-serialized form.
   *
   * This payload is the exact serialized `VersionedHtlcOrderDetails` whose
   * hash is embedded into the order being built.
   *
   * The same bytes should later be passed to `RegisterSignedOrderRequest`.
   * Resolvers can hash this payload and compare it with the hash committed in
   * the signed order or escrow-backed position to verify that the trader signed
   * this exact intent.
   *
   * The payload is returned in serialized form to avoid differences in binary
   * representation after a deserialize-serialize cycle.
   */
  serializedOrderDetails?: Uint8Array | undefined;
}

/** Input parameters for building an unsigned EVM order-cancellation payload. */
export interface BuildEvmOrderCancellationRequest {
  /** ID of the quote corresponding to the order being cancelled. */
  quoteId: string;
  /**
   * The address on **Source** blockchain that will sign the cancellation.
   *
   * This address must match the wallet that signed the corresponding **Signed
   * Order**.
   */
  ownerSrcAddress: ChainAddress;
}

/** Unsigned EVM cancellation payload ready for signing. */
export interface EvmOrderCancellationResponse {
  /**
   * Json structure that contains TypedData param for signing with
   * `eth_signTypedData` as specified by EIP-712.
   *
   * This message includes at least required `types`, `primaryType`, `domain`
   * and `message` fields.
   */
  typedData: string;
}

function createBaseBuildEvmOrderPayloadRequest(): BuildEvmOrderPayloadRequest {
  return {
    quoteId: "",
    ownerSrcAddress: undefined,
    traderDstAddress: undefined,
    htlcSecrets: undefined,
    traderDstDiscloseAddress: undefined,
  };
}

export const BuildEvmOrderPayloadRequest: MessageFns<BuildEvmOrderPayloadRequest> = {
  fromJSON(object: any): BuildEvmOrderPayloadRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      ownerSrcAddress: isSet(object.owner_src_address)
        ? ChainAddress.fromJSON(object.owner_src_address)
        : undefined,
      traderDstAddress: isSet(object.trader_dst_address)
        ? ChainAddress.fromJSON(object.trader_dst_address)
        : undefined,
      htlcSecrets: isSet(object.htlc_secrets)
        ? HtlcSecrets.fromJSON(object.htlc_secrets)
        : undefined,
      traderDstDiscloseAddress: isSet(object.trader_dst_disclose_address)
        ? ChainAddress.fromJSON(object.trader_dst_disclose_address)
        : undefined,
    };
  },

  toJSON(message: BuildEvmOrderPayloadRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.ownerSrcAddress !== undefined) {
      obj.owner_src_address = ChainAddress.toJSON(message.ownerSrcAddress);
    }
    if (message.traderDstAddress !== undefined) {
      obj.trader_dst_address = ChainAddress.toJSON(message.traderDstAddress);
    }
    if (message.htlcSecrets !== undefined) {
      obj.htlc_secrets = HtlcSecrets.toJSON(message.htlcSecrets);
    }
    if (message.traderDstDiscloseAddress !== undefined) {
      obj.trader_dst_disclose_address = ChainAddress.toJSON(message.traderDstDiscloseAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildEvmOrderPayloadRequest>, I>>(
    base?: I,
  ): BuildEvmOrderPayloadRequest {
    return BuildEvmOrderPayloadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildEvmOrderPayloadRequest>, I>>(
    object: I,
  ): BuildEvmOrderPayloadRequest {
    const message = createBaseBuildEvmOrderPayloadRequest();
    message.quoteId = object.quoteId ?? "";
    message.ownerSrcAddress =
      object.ownerSrcAddress !== undefined && object.ownerSrcAddress !== null
        ? ChainAddress.fromPartial(object.ownerSrcAddress)
        : undefined;
    message.traderDstAddress =
      object.traderDstAddress !== undefined && object.traderDstAddress !== null
        ? ChainAddress.fromPartial(object.traderDstAddress)
        : undefined;
    message.htlcSecrets =
      object.htlcSecrets !== undefined && object.htlcSecrets !== null
        ? HtlcSecrets.fromPartial(object.htlcSecrets)
        : undefined;
    message.traderDstDiscloseAddress =
      object.traderDstDiscloseAddress !== undefined && object.traderDstDiscloseAddress !== null
        ? ChainAddress.fromPartial(object.traderDstDiscloseAddress)
        : undefined;
    return message;
  },
};

function createBaseEvmOrderPayloadResponse(): EvmOrderPayloadResponse {
  return { typedData: "", orderExtension: new Uint8Array(0), serializedOrderDetails: undefined };
}

export const EvmOrderPayloadResponse: MessageFns<EvmOrderPayloadResponse> = {
  fromJSON(object: any): EvmOrderPayloadResponse {
    return {
      typedData: isSet(object.typed_data) ? globalThis.String(object.typed_data) : "",
      orderExtension: isSet(object.order_extension)
        ? bytesFromBase64(object.order_extension)
        : new Uint8Array(0),
      serializedOrderDetails: isSet(object.serialized_order_details)
        ? bytesFromBase64(object.serialized_order_details)
        : undefined,
    };
  },

  toJSON(message: EvmOrderPayloadResponse): unknown {
    const obj: any = {};
    if (message.typedData !== undefined) {
      obj.typed_data = message.typedData;
    }
    if (message.orderExtension !== undefined) {
      obj.order_extension = base64FromBytes(message.orderExtension);
    }
    if (message.serializedOrderDetails !== undefined) {
      obj.serialized_order_details = base64FromBytes(message.serializedOrderDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EvmOrderPayloadResponse>, I>>(
    base?: I,
  ): EvmOrderPayloadResponse {
    return EvmOrderPayloadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EvmOrderPayloadResponse>, I>>(
    object: I,
  ): EvmOrderPayloadResponse {
    const message = createBaseEvmOrderPayloadResponse();
    message.typedData = object.typedData ?? "";
    message.orderExtension = object.orderExtension ?? new Uint8Array(0);
    message.serializedOrderDetails = object.serializedOrderDetails ?? undefined;
    return message;
  },
};

function createBaseBuildEvmOrderCancellationRequest(): BuildEvmOrderCancellationRequest {
  return { quoteId: "", ownerSrcAddress: undefined };
}

export const BuildEvmOrderCancellationRequest: MessageFns<BuildEvmOrderCancellationRequest> = {
  fromJSON(object: any): BuildEvmOrderCancellationRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      ownerSrcAddress: isSet(object.owner_src_address)
        ? ChainAddress.fromJSON(object.owner_src_address)
        : undefined,
    };
  },

  toJSON(message: BuildEvmOrderCancellationRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.ownerSrcAddress !== undefined) {
      obj.owner_src_address = ChainAddress.toJSON(message.ownerSrcAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildEvmOrderCancellationRequest>, I>>(
    base?: I,
  ): BuildEvmOrderCancellationRequest {
    return BuildEvmOrderCancellationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildEvmOrderCancellationRequest>, I>>(
    object: I,
  ): BuildEvmOrderCancellationRequest {
    const message = createBaseBuildEvmOrderCancellationRequest();
    message.quoteId = object.quoteId ?? "";
    message.ownerSrcAddress =
      object.ownerSrcAddress !== undefined && object.ownerSrcAddress !== null
        ? ChainAddress.fromPartial(object.ownerSrcAddress)
        : undefined;
    return message;
  },
};

function createBaseEvmOrderCancellationResponse(): EvmOrderCancellationResponse {
  return { typedData: "" };
}

export const EvmOrderCancellationResponse: MessageFns<EvmOrderCancellationResponse> = {
  fromJSON(object: any): EvmOrderCancellationResponse {
    return { typedData: isSet(object.typed_data) ? globalThis.String(object.typed_data) : "" };
  },

  toJSON(message: EvmOrderCancellationResponse): unknown {
    const obj: any = {};
    if (message.typedData !== undefined) {
      obj.typed_data = message.typedData;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EvmOrderCancellationResponse>, I>>(
    base?: I,
  ): EvmOrderCancellationResponse {
    return EvmOrderCancellationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EvmOrderCancellationResponse>, I>>(
    object: I,
  ): EvmOrderCancellationResponse {
    const message = createBaseEvmOrderCancellationResponse();
    message.typedData = object.typedData ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
