// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: stonfi/omni/v1beta8/trader/chains/ton.proto

// @ts-nocheck
// oxlint-disable

import { AssetId } from "../../../../common/v1/types/asset_id";
import { ChainAddress } from "../../../../common/v1/types/chain_address";
import { HtlcSecrets } from "../../types/htlc";

export interface TonEscrowVaultBalancesRequest {
  /** Address of the owner. */
  ownerAddress: ChainAddress;
  /**
   * Optional address of **Escrow factory** .
   *
   * If omitted, return vault balance for all factories.
   */
  escrowFactoryAddress?: ChainAddress | undefined;
  /**
   * Optional address of the asset.
   *
   * If omitted, return vault balance for all assets.
   */
  assetAddress?: AssetId | undefined;
}

/** Balance information for one owner / factory / asset vault entry. */
export interface TonVaultBalance {
  factoryAddress: ChainAddress;
  assetAddress: AssetId;
  amountUnits: string;
}

/** Vault balances grouped for a specific owner. */
export interface TonEscrowVaultBalancesResponse {
  ownerAddress: ChainAddress;
  balances: TonVaultBalance[];
}

/** A request to generate unsigned transfer to initiate the swap. */
export interface BuildTonSwapRequest {
  /** The ID of quote received from `QuoteRpc` */
  quoteId: string;
  /**
   * The address on **Source** blockchain that will send initial transaction to
   * start the trade
   */
  transferSrcAddress: ChainAddress;
  /**
   * The address on **Destination** blockchain that will receive result of the
   * trade
   *
   * If omitted, use transfer_src_address
   */
  traderDstAddress?: ChainAddress | undefined;
  /**
   * The address on **Source** blockchain that will receive the gas not spent by
   * the trade.
   *
   * If omitted, use transfer_src_address
   */
  gasExcessAddress?: ChainAddress | undefined;
  /**
   * The address on **Source** blockchain to which funds will be returned in
   * case of an failure.
   *
   * If omitted, use transfer_src_address
   */
  refundSrcAddress?: ChainAddress | undefined;
  /**
   * Use the slippage recommended by Omniston instead of slippage provided by
   * trader in QuoteRequest.
   */
  useRecommendedSlippage?: boolean | undefined;
}

/**
 * A request to generate unsigned transfer to create a position on escrow
 * contract for specified quote.
 */
export interface BuildTonEscrowTransferRequest {
  /** The ID of quote received from `QuoteRpc` */
  quoteId: string;
  /**
   * The address on **Source** blockchain that will own created position, can
   * withdraw tokens and will receive withdrawn tokens.
   */
  ownerSrcAddress: ChainAddress;
  /**
   * The address on **Destination** blockchain that will receive result of the
   * trade
   */
  traderDstAddress?: ChainAddress | undefined;
  /**
   * The address on **Source** blockchain that will send initial transaction to
   * create the escrow position.
   *
   * If omitted, `owner_src_address` will be used.
   */
  transferSrcAddress?: ChainAddress | undefined;
  /**
   * The address that will receive the gas not spent by the trade.
   *
   * If omitted, `owner_src_address` will be used.
   */
  gasExcessAddress?: ChainAddress | undefined;
  /**
   * The address to which funds will be returned in case of an failed creation
   * of the position.
   *
   * If omitted, `owner_src_address` will be used.
   */
  refundSrcAddress?: ChainAddress | undefined;
  /**
   * Specifies whether the **Input asset** will be deposited from the vault of
   * escrow contract.
   *
   * False by default
   */
  depositViaVault?: boolean | undefined;
  /**
   * Specifies whether the **Input asset** will be refunded to the vault of
   * escrow contract in case of error.
   *
   * False by default
   */
  refundToVault?: boolean | undefined;
  /**
   * (HTLC-only) Allows to specify how the secrets for a multi-chunk HTLC
   * position should be defined.
   *
   * This parameter should be omitted for intrachain swaps
   */
  htlcSecrets?: HtlcSecrets | undefined;
  /**
   * (HTLC-only) The address on **Destination blockchain** that can disclose the
   * secret to claim the **Output position**.
   *
   * This address should be omitted when using public disclosure of the secret.
   */
  traderDstDiscloseAddress?: ChainAddress | undefined;
}

/** Input parameters for building a TON escrow-cancellation transaction. */
export interface BuildTonEscrowCancellationRequest {
  /** The ID of quote received from `QuoteRpc` */
  quoteId: string;
  /**
   * The address that will send the cancellation transaction.
   *
   * The **Escrow position** must be created by the same wallet.
   */
  ownerAddress: ChainAddress;
  /**
   * The address that will receive the gas not spent by the cancellation.
   *
   * If omitted, use owner_address
   */
  gasExcessAddress?: ChainAddress | undefined;
}

function createBaseTonEscrowVaultBalancesRequest(): TonEscrowVaultBalancesRequest {
  return { ownerAddress: undefined, escrowFactoryAddress: undefined, assetAddress: undefined };
}

export const TonEscrowVaultBalancesRequest: MessageFns<TonEscrowVaultBalancesRequest> = {
  fromJSON(object: any): TonEscrowVaultBalancesRequest {
    return {
      ownerAddress: isSet(object.owner_address)
        ? ChainAddress.fromJSON(object.owner_address)
        : undefined,
      escrowFactoryAddress: isSet(object.escrow_factory_address)
        ? ChainAddress.fromJSON(object.escrow_factory_address)
        : undefined,
      assetAddress: isSet(object.asset_address)
        ? AssetId.fromJSON(object.asset_address)
        : undefined,
    };
  },

  toJSON(message: TonEscrowVaultBalancesRequest): unknown {
    const obj: any = {};
    if (message.ownerAddress !== undefined) {
      obj.owner_address = ChainAddress.toJSON(message.ownerAddress);
    }
    if (message.escrowFactoryAddress !== undefined) {
      obj.escrow_factory_address = ChainAddress.toJSON(message.escrowFactoryAddress);
    }
    if (message.assetAddress !== undefined) {
      obj.asset_address = AssetId.toJSON(message.assetAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonEscrowVaultBalancesRequest>, I>>(
    base?: I,
  ): TonEscrowVaultBalancesRequest {
    return TonEscrowVaultBalancesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonEscrowVaultBalancesRequest>, I>>(
    object: I,
  ): TonEscrowVaultBalancesRequest {
    const message = createBaseTonEscrowVaultBalancesRequest();
    message.ownerAddress =
      object.ownerAddress !== undefined && object.ownerAddress !== null
        ? ChainAddress.fromPartial(object.ownerAddress)
        : undefined;
    message.escrowFactoryAddress =
      object.escrowFactoryAddress !== undefined && object.escrowFactoryAddress !== null
        ? ChainAddress.fromPartial(object.escrowFactoryAddress)
        : undefined;
    message.assetAddress =
      object.assetAddress !== undefined && object.assetAddress !== null
        ? AssetId.fromPartial(object.assetAddress)
        : undefined;
    return message;
  },
};

function createBaseTonVaultBalance(): TonVaultBalance {
  return { factoryAddress: undefined, assetAddress: undefined, amountUnits: "" };
}

export const TonVaultBalance: MessageFns<TonVaultBalance> = {
  fromJSON(object: any): TonVaultBalance {
    return {
      factoryAddress: isSet(object.factory_address)
        ? ChainAddress.fromJSON(object.factory_address)
        : undefined,
      assetAddress: isSet(object.asset_address)
        ? AssetId.fromJSON(object.asset_address)
        : undefined,
      amountUnits: isSet(object.amount_units) ? globalThis.String(object.amount_units) : "",
    };
  },

  toJSON(message: TonVaultBalance): unknown {
    const obj: any = {};
    if (message.factoryAddress !== undefined) {
      obj.factory_address = ChainAddress.toJSON(message.factoryAddress);
    }
    if (message.assetAddress !== undefined) {
      obj.asset_address = AssetId.toJSON(message.assetAddress);
    }
    if (message.amountUnits !== undefined) {
      obj.amount_units = message.amountUnits;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonVaultBalance>, I>>(base?: I): TonVaultBalance {
    return TonVaultBalance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonVaultBalance>, I>>(object: I): TonVaultBalance {
    const message = createBaseTonVaultBalance();
    message.factoryAddress =
      object.factoryAddress !== undefined && object.factoryAddress !== null
        ? ChainAddress.fromPartial(object.factoryAddress)
        : undefined;
    message.assetAddress =
      object.assetAddress !== undefined && object.assetAddress !== null
        ? AssetId.fromPartial(object.assetAddress)
        : undefined;
    message.amountUnits = object.amountUnits ?? "";
    return message;
  },
};

function createBaseTonEscrowVaultBalancesResponse(): TonEscrowVaultBalancesResponse {
  return { ownerAddress: undefined, balances: [] };
}

export const TonEscrowVaultBalancesResponse: MessageFns<TonEscrowVaultBalancesResponse> = {
  fromJSON(object: any): TonEscrowVaultBalancesResponse {
    return {
      ownerAddress: isSet(object.owner_address)
        ? ChainAddress.fromJSON(object.owner_address)
        : undefined,
      balances: globalThis.Array.isArray(object?.balances)
        ? object.balances.map((e: any) => TonVaultBalance.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TonEscrowVaultBalancesResponse): unknown {
    const obj: any = {};
    if (message.ownerAddress !== undefined) {
      obj.owner_address = ChainAddress.toJSON(message.ownerAddress);
    }
    if (message.balances?.length) {
      obj.balances = message.balances.map((e) => TonVaultBalance.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TonEscrowVaultBalancesResponse>, I>>(
    base?: I,
  ): TonEscrowVaultBalancesResponse {
    return TonEscrowVaultBalancesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TonEscrowVaultBalancesResponse>, I>>(
    object: I,
  ): TonEscrowVaultBalancesResponse {
    const message = createBaseTonEscrowVaultBalancesResponse();
    message.ownerAddress =
      object.ownerAddress !== undefined && object.ownerAddress !== null
        ? ChainAddress.fromPartial(object.ownerAddress)
        : undefined;
    message.balances = object.balances?.map((e) => TonVaultBalance.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBuildTonSwapRequest(): BuildTonSwapRequest {
  return {
    quoteId: "",
    transferSrcAddress: undefined,
    traderDstAddress: undefined,
    gasExcessAddress: undefined,
    refundSrcAddress: undefined,
    useRecommendedSlippage: undefined,
  };
}

export const BuildTonSwapRequest: MessageFns<BuildTonSwapRequest> = {
  fromJSON(object: any): BuildTonSwapRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      transferSrcAddress: isSet(object.transfer_src_address)
        ? ChainAddress.fromJSON(object.transfer_src_address)
        : undefined,
      traderDstAddress: isSet(object.trader_dst_address)
        ? ChainAddress.fromJSON(object.trader_dst_address)
        : undefined,
      gasExcessAddress: isSet(object.gas_excess_address)
        ? ChainAddress.fromJSON(object.gas_excess_address)
        : undefined,
      refundSrcAddress: isSet(object.refund_src_address)
        ? ChainAddress.fromJSON(object.refund_src_address)
        : undefined,
      useRecommendedSlippage: isSet(object.use_recommended_slippage)
        ? globalThis.Boolean(object.use_recommended_slippage)
        : undefined,
    };
  },

  toJSON(message: BuildTonSwapRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.transferSrcAddress !== undefined) {
      obj.transfer_src_address = ChainAddress.toJSON(message.transferSrcAddress);
    }
    if (message.traderDstAddress !== undefined) {
      obj.trader_dst_address = ChainAddress.toJSON(message.traderDstAddress);
    }
    if (message.gasExcessAddress !== undefined) {
      obj.gas_excess_address = ChainAddress.toJSON(message.gasExcessAddress);
    }
    if (message.refundSrcAddress !== undefined) {
      obj.refund_src_address = ChainAddress.toJSON(message.refundSrcAddress);
    }
    if (message.useRecommendedSlippage !== undefined) {
      obj.use_recommended_slippage = message.useRecommendedSlippage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildTonSwapRequest>, I>>(base?: I): BuildTonSwapRequest {
    return BuildTonSwapRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildTonSwapRequest>, I>>(
    object: I,
  ): BuildTonSwapRequest {
    const message = createBaseBuildTonSwapRequest();
    message.quoteId = object.quoteId ?? "";
    message.transferSrcAddress =
      object.transferSrcAddress !== undefined && object.transferSrcAddress !== null
        ? ChainAddress.fromPartial(object.transferSrcAddress)
        : undefined;
    message.traderDstAddress =
      object.traderDstAddress !== undefined && object.traderDstAddress !== null
        ? ChainAddress.fromPartial(object.traderDstAddress)
        : undefined;
    message.gasExcessAddress =
      object.gasExcessAddress !== undefined && object.gasExcessAddress !== null
        ? ChainAddress.fromPartial(object.gasExcessAddress)
        : undefined;
    message.refundSrcAddress =
      object.refundSrcAddress !== undefined && object.refundSrcAddress !== null
        ? ChainAddress.fromPartial(object.refundSrcAddress)
        : undefined;
    message.useRecommendedSlippage = object.useRecommendedSlippage ?? undefined;
    return message;
  },
};

function createBaseBuildTonEscrowTransferRequest(): BuildTonEscrowTransferRequest {
  return {
    quoteId: "",
    ownerSrcAddress: undefined,
    traderDstAddress: undefined,
    transferSrcAddress: undefined,
    gasExcessAddress: undefined,
    refundSrcAddress: undefined,
    depositViaVault: undefined,
    refundToVault: undefined,
    htlcSecrets: undefined,
    traderDstDiscloseAddress: undefined,
  };
}

export const BuildTonEscrowTransferRequest: MessageFns<BuildTonEscrowTransferRequest> = {
  fromJSON(object: any): BuildTonEscrowTransferRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      ownerSrcAddress: isSet(object.owner_src_address)
        ? ChainAddress.fromJSON(object.owner_src_address)
        : undefined,
      traderDstAddress: isSet(object.trader_dst_address)
        ? ChainAddress.fromJSON(object.trader_dst_address)
        : undefined,
      transferSrcAddress: isSet(object.transfer_src_address)
        ? ChainAddress.fromJSON(object.transfer_src_address)
        : undefined,
      gasExcessAddress: isSet(object.gas_excess_address)
        ? ChainAddress.fromJSON(object.gas_excess_address)
        : undefined,
      refundSrcAddress: isSet(object.refund_src_address)
        ? ChainAddress.fromJSON(object.refund_src_address)
        : undefined,
      depositViaVault: isSet(object.deposit_via_vault)
        ? globalThis.Boolean(object.deposit_via_vault)
        : undefined,
      refundToVault: isSet(object.refund_to_vault)
        ? globalThis.Boolean(object.refund_to_vault)
        : undefined,
      htlcSecrets: isSet(object.htlc_secrets)
        ? HtlcSecrets.fromJSON(object.htlc_secrets)
        : undefined,
      traderDstDiscloseAddress: isSet(object.trader_dst_disclose_address)
        ? ChainAddress.fromJSON(object.trader_dst_disclose_address)
        : undefined,
    };
  },

  toJSON(message: BuildTonEscrowTransferRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.ownerSrcAddress !== undefined) {
      obj.owner_src_address = ChainAddress.toJSON(message.ownerSrcAddress);
    }
    if (message.traderDstAddress !== undefined) {
      obj.trader_dst_address = ChainAddress.toJSON(message.traderDstAddress);
    }
    if (message.transferSrcAddress !== undefined) {
      obj.transfer_src_address = ChainAddress.toJSON(message.transferSrcAddress);
    }
    if (message.gasExcessAddress !== undefined) {
      obj.gas_excess_address = ChainAddress.toJSON(message.gasExcessAddress);
    }
    if (message.refundSrcAddress !== undefined) {
      obj.refund_src_address = ChainAddress.toJSON(message.refundSrcAddress);
    }
    if (message.depositViaVault !== undefined) {
      obj.deposit_via_vault = message.depositViaVault;
    }
    if (message.refundToVault !== undefined) {
      obj.refund_to_vault = message.refundToVault;
    }
    if (message.htlcSecrets !== undefined) {
      obj.htlc_secrets = HtlcSecrets.toJSON(message.htlcSecrets);
    }
    if (message.traderDstDiscloseAddress !== undefined) {
      obj.trader_dst_disclose_address = ChainAddress.toJSON(message.traderDstDiscloseAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildTonEscrowTransferRequest>, I>>(
    base?: I,
  ): BuildTonEscrowTransferRequest {
    return BuildTonEscrowTransferRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildTonEscrowTransferRequest>, I>>(
    object: I,
  ): BuildTonEscrowTransferRequest {
    const message = createBaseBuildTonEscrowTransferRequest();
    message.quoteId = object.quoteId ?? "";
    message.ownerSrcAddress =
      object.ownerSrcAddress !== undefined && object.ownerSrcAddress !== null
        ? ChainAddress.fromPartial(object.ownerSrcAddress)
        : undefined;
    message.traderDstAddress =
      object.traderDstAddress !== undefined && object.traderDstAddress !== null
        ? ChainAddress.fromPartial(object.traderDstAddress)
        : undefined;
    message.transferSrcAddress =
      object.transferSrcAddress !== undefined && object.transferSrcAddress !== null
        ? ChainAddress.fromPartial(object.transferSrcAddress)
        : undefined;
    message.gasExcessAddress =
      object.gasExcessAddress !== undefined && object.gasExcessAddress !== null
        ? ChainAddress.fromPartial(object.gasExcessAddress)
        : undefined;
    message.refundSrcAddress =
      object.refundSrcAddress !== undefined && object.refundSrcAddress !== null
        ? ChainAddress.fromPartial(object.refundSrcAddress)
        : undefined;
    message.depositViaVault = object.depositViaVault ?? undefined;
    message.refundToVault = object.refundToVault ?? undefined;
    message.htlcSecrets =
      object.htlcSecrets !== undefined && object.htlcSecrets !== null
        ? HtlcSecrets.fromPartial(object.htlcSecrets)
        : undefined;
    message.traderDstDiscloseAddress =
      object.traderDstDiscloseAddress !== undefined && object.traderDstDiscloseAddress !== null
        ? ChainAddress.fromPartial(object.traderDstDiscloseAddress)
        : undefined;
    return message;
  },
};

function createBaseBuildTonEscrowCancellationRequest(): BuildTonEscrowCancellationRequest {
  return { quoteId: "", ownerAddress: undefined, gasExcessAddress: undefined };
}

export const BuildTonEscrowCancellationRequest: MessageFns<BuildTonEscrowCancellationRequest> = {
  fromJSON(object: any): BuildTonEscrowCancellationRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      ownerAddress: isSet(object.owner_address)
        ? ChainAddress.fromJSON(object.owner_address)
        : undefined,
      gasExcessAddress: isSet(object.gas_excess_address)
        ? ChainAddress.fromJSON(object.gas_excess_address)
        : undefined,
    };
  },

  toJSON(message: BuildTonEscrowCancellationRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.ownerAddress !== undefined) {
      obj.owner_address = ChainAddress.toJSON(message.ownerAddress);
    }
    if (message.gasExcessAddress !== undefined) {
      obj.gas_excess_address = ChainAddress.toJSON(message.gasExcessAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildTonEscrowCancellationRequest>, I>>(
    base?: I,
  ): BuildTonEscrowCancellationRequest {
    return BuildTonEscrowCancellationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildTonEscrowCancellationRequest>, I>>(
    object: I,
  ): BuildTonEscrowCancellationRequest {
    const message = createBaseBuildTonEscrowCancellationRequest();
    message.quoteId = object.quoteId ?? "";
    message.ownerAddress =
      object.ownerAddress !== undefined && object.ownerAddress !== null
        ? ChainAddress.fromPartial(object.ownerAddress)
        : undefined;
    message.gasExcessAddress =
      object.gasExcessAddress !== undefined && object.gasExcessAddress !== null
        ? ChainAddress.fromPartial(object.gasExcessAddress)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { $case: string; value: unknown }
        ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
        : T extends {}
          ? { [K in keyof T]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
