// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.0
//   protoc               v6.33.0
// source: omni/v1beta7/trader/escrow.proto

/* eslint-disable */
//biome-ignore-all : autogenerated file, no need to check

export const protobufPackage = "";
