// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.31.1
// source: omni/v1beta7/trader/escrow.proto

/* eslint-disable */

export const protobufPackage = "";
