// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.0
//   protoc               v6.33.0
// source: omni/v1beta7/trader/escrow.proto

/* eslint-disable */
//biome-ignore-all : autogenerated file, no need to check

import { Address } from "../types/common";
import { Quote } from "../types/quote";

export const protobufPackage = "omni.v1beta7";

export interface EscrowOrderListRequest {
  /** The address of trader's wallet that initiated transaction to create the orders */
  traderWalletAddress: Address | undefined;
}

export interface EscrowOrderList {
  orders: EscrowOrderData[];
}

export interface EscrowOrderData {
  quote: Quote | undefined;
  escrowItemAddress: Address | undefined;
  /** Hash of tx outgoing from the wallet to create the order */
  outgoingTxHash: string;
}

function createBaseEscrowOrderListRequest(): EscrowOrderListRequest {
  return { traderWalletAddress: undefined };
}

export const EscrowOrderListRequest: MessageFns<EscrowOrderListRequest> = {
  fromJSON(object: any): EscrowOrderListRequest {
    return {
      traderWalletAddress: isSet(object.trader_wallet_address)
        ? Address.fromJSON(object.trader_wallet_address)
        : undefined,
    };
  },

  toJSON(message: EscrowOrderListRequest): unknown {
    const obj: any = {};
    if (message.traderWalletAddress !== undefined) {
      obj.trader_wallet_address = Address.toJSON(message.traderWalletAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EscrowOrderListRequest>, I>>(
    base?: I,
  ): EscrowOrderListRequest {
    return EscrowOrderListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EscrowOrderListRequest>, I>>(
    object: I,
  ): EscrowOrderListRequest {
    const message = createBaseEscrowOrderListRequest();
    message.traderWalletAddress =
      object.traderWalletAddress !== undefined &&
      object.traderWalletAddress !== null
        ? Address.fromPartial(object.traderWalletAddress)
        : undefined;
    return message;
  },
};

function createBaseEscrowOrderList(): EscrowOrderList {
  return { orders: [] };
}

export const EscrowOrderList: MessageFns<EscrowOrderList> = {
  fromJSON(object: any): EscrowOrderList {
    return {
      orders: globalThis.Array.isArray(object?.orders)
        ? object.orders.map((e: any) => EscrowOrderData.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EscrowOrderList): unknown {
    const obj: any = {};
    if (message.orders?.length) {
      obj.orders = message.orders.map((e) => EscrowOrderData.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EscrowOrderList>, I>>(
    base?: I,
  ): EscrowOrderList {
    return EscrowOrderList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EscrowOrderList>, I>>(
    object: I,
  ): EscrowOrderList {
    const message = createBaseEscrowOrderList();
    message.orders =
      object.orders?.map((e) => EscrowOrderData.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEscrowOrderData(): EscrowOrderData {
  return { quote: undefined, escrowItemAddress: undefined, outgoingTxHash: "" };
}

export const EscrowOrderData: MessageFns<EscrowOrderData> = {
  fromJSON(object: any): EscrowOrderData {
    return {
      quote: isSet(object.quote) ? Quote.fromJSON(object.quote) : undefined,
      escrowItemAddress: isSet(object.escrow_item_address)
        ? Address.fromJSON(object.escrow_item_address)
        : undefined,
      outgoingTxHash: isSet(object.outgoing_tx_hash)
        ? globalThis.String(object.outgoing_tx_hash)
        : "",
    };
  },

  toJSON(message: EscrowOrderData): unknown {
    const obj: any = {};
    if (message.quote !== undefined) {
      obj.quote = Quote.toJSON(message.quote);
    }
    if (message.escrowItemAddress !== undefined) {
      obj.escrow_item_address = Address.toJSON(message.escrowItemAddress);
    }
    if (message.outgoingTxHash !== undefined) {
      obj.outgoing_tx_hash = message.outgoingTxHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EscrowOrderData>, I>>(
    base?: I,
  ): EscrowOrderData {
    return EscrowOrderData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EscrowOrderData>, I>>(
    object: I,
  ): EscrowOrderData {
    const message = createBaseEscrowOrderData();
    message.quote =
      object.quote !== undefined && object.quote !== null
        ? Quote.fromPartial(object.quote)
        : undefined;
    message.escrowItemAddress =
      object.escrowItemAddress !== undefined &&
      object.escrowItemAddress !== null
        ? Address.fromPartial(object.escrowItemAddress)
        : undefined;
    message.outgoingTxHash = object.outgoingTxHash ?? "";
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
