// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.0
//   protoc               v6.33.0
// source: omni/v1beta7/trader/gasless.proto

/* eslint-disable */
//biome-ignore-all : autogenerated file, no need to check

import { Address } from "../types/common";
import {
  GaslessCancellation,
  GaslessOrder,
  GaslessPayload,
} from "../types/gasless";
import { OrderData } from "../types/order";
import { Quote } from "../types/quote";

export const protobufPackage = "omni.v1beta7";

/** TODO: unstable API */
export interface BuildRequest {
  /** The address on `bid_blockchain` that will send initial transaction to start the trade */
  sourceAddress: Address | undefined;
  /** The valid quote received from `QuoteGrpc` */
  quote: Quote | undefined;
}

/** TODO: unstable API */
export interface BuildResponse {
  /** Payload to be signed by user. */
  payload: GaslessPayload | undefined;
}

/** TODO: unstable API */
export interface PlaceRequest {
  /** ID of the Quote that has been used to produce corresponding payload. */
  quoteId: string;
  /**
   * Public key that has been used to sign the message.
   * This key must be used to cancel the order.
   */
  publicKey: number[];
  /** Signed gasless order */
  order: GaslessOrder | undefined;
}

/** TODO: unstable API */
export interface PlaceResponse {
  /** TODO: Replace with enum (or maybe just remove it) */
  status: string;
}

/** TODO: unstable API */
export interface ListRequest {
  sourceAddress: Address | undefined;
}

/** TODO: unstable API */
export interface OrderList {
  orders: OrderData[];
}

/** TODO: unstable API */
export interface CancelRequest {
  quoteId: string;
  cancellation: GaslessCancellation | undefined;
}

/** TODO: unstable API */
export interface CancelResponse {
  status: string;
}

function createBaseBuildRequest(): BuildRequest {
  return { sourceAddress: undefined, quote: undefined };
}

export const BuildRequest: MessageFns<BuildRequest> = {
  fromJSON(object: any): BuildRequest {
    return {
      sourceAddress: isSet(object.source_address)
        ? Address.fromJSON(object.source_address)
        : undefined,
      quote: isSet(object.quote) ? Quote.fromJSON(object.quote) : undefined,
    };
  },

  toJSON(message: BuildRequest): unknown {
    const obj: any = {};
    if (message.sourceAddress !== undefined) {
      obj.source_address = Address.toJSON(message.sourceAddress);
    }
    if (message.quote !== undefined) {
      obj.quote = Quote.toJSON(message.quote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildRequest>, I>>(
    base?: I,
  ): BuildRequest {
    return BuildRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildRequest>, I>>(
    object: I,
  ): BuildRequest {
    const message = createBaseBuildRequest();
    message.sourceAddress =
      object.sourceAddress !== undefined && object.sourceAddress !== null
        ? Address.fromPartial(object.sourceAddress)
        : undefined;
    message.quote =
      object.quote !== undefined && object.quote !== null
        ? Quote.fromPartial(object.quote)
        : undefined;
    return message;
  },
};

function createBaseBuildResponse(): BuildResponse {
  return { payload: undefined };
}

export const BuildResponse: MessageFns<BuildResponse> = {
  fromJSON(object: any): BuildResponse {
    return {
      payload: isSet(object.payload)
        ? GaslessPayload.fromJSON(object.payload)
        : undefined,
    };
  },

  toJSON(message: BuildResponse): unknown {
    const obj: any = {};
    if (message.payload !== undefined) {
      obj.payload = GaslessPayload.toJSON(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildResponse>, I>>(
    base?: I,
  ): BuildResponse {
    return BuildResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildResponse>, I>>(
    object: I,
  ): BuildResponse {
    const message = createBaseBuildResponse();
    message.payload =
      object.payload !== undefined && object.payload !== null
        ? GaslessPayload.fromPartial(object.payload)
        : undefined;
    return message;
  },
};

function createBasePlaceRequest(): PlaceRequest {
  return { quoteId: "", publicKey: [], order: undefined };
}

export const PlaceRequest: MessageFns<PlaceRequest> = {
  fromJSON(object: any): PlaceRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      publicKey: globalThis.Array.isArray(object?.public_key)
        ? object.public_key.map((e: any) => globalThis.Number(e))
        : [],
      order: isSet(object.order)
        ? GaslessOrder.fromJSON(object.order)
        : undefined,
    };
  },

  toJSON(message: PlaceRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.publicKey?.length) {
      obj.public_key = message.publicKey.map((e) => Math.round(e));
    }
    if (message.order !== undefined) {
      obj.order = GaslessOrder.toJSON(message.order);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlaceRequest>, I>>(
    base?: I,
  ): PlaceRequest {
    return PlaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlaceRequest>, I>>(
    object: I,
  ): PlaceRequest {
    const message = createBasePlaceRequest();
    message.quoteId = object.quoteId ?? "";
    message.publicKey = object.publicKey?.map((e) => e) || [];
    message.order =
      object.order !== undefined && object.order !== null
        ? GaslessOrder.fromPartial(object.order)
        : undefined;
    return message;
  },
};

function createBasePlaceResponse(): PlaceResponse {
  return { status: "" };
}

export const PlaceResponse: MessageFns<PlaceResponse> = {
  fromJSON(object: any): PlaceResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: PlaceResponse): unknown {
    const obj: any = {};
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlaceResponse>, I>>(
    base?: I,
  ): PlaceResponse {
    return PlaceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlaceResponse>, I>>(
    object: I,
  ): PlaceResponse {
    const message = createBasePlaceResponse();
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseListRequest(): ListRequest {
  return { sourceAddress: undefined };
}

export const ListRequest: MessageFns<ListRequest> = {
  fromJSON(object: any): ListRequest {
    return {
      sourceAddress: isSet(object.source_address)
        ? Address.fromJSON(object.source_address)
        : undefined,
    };
  },

  toJSON(message: ListRequest): unknown {
    const obj: any = {};
    if (message.sourceAddress !== undefined) {
      obj.source_address = Address.toJSON(message.sourceAddress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListRequest>, I>>(base?: I): ListRequest {
    return ListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListRequest>, I>>(
    object: I,
  ): ListRequest {
    const message = createBaseListRequest();
    message.sourceAddress =
      object.sourceAddress !== undefined && object.sourceAddress !== null
        ? Address.fromPartial(object.sourceAddress)
        : undefined;
    return message;
  },
};

function createBaseOrderList(): OrderList {
  return { orders: [] };
}

export const OrderList: MessageFns<OrderList> = {
  fromJSON(object: any): OrderList {
    return {
      orders: globalThis.Array.isArray(object?.orders)
        ? object.orders.map((e: any) => OrderData.fromJSON(e))
        : [],
    };
  },

  toJSON(message: OrderList): unknown {
    const obj: any = {};
    if (message.orders?.length) {
      obj.orders = message.orders.map((e) => OrderData.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderList>, I>>(base?: I): OrderList {
    return OrderList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderList>, I>>(
    object: I,
  ): OrderList {
    const message = createBaseOrderList();
    message.orders = object.orders?.map((e) => OrderData.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCancelRequest(): CancelRequest {
  return { quoteId: "", cancellation: undefined };
}

export const CancelRequest: MessageFns<CancelRequest> = {
  fromJSON(object: any): CancelRequest {
    return {
      quoteId: isSet(object.quote_id) ? globalThis.String(object.quote_id) : "",
      cancellation: isSet(object.cancellation)
        ? GaslessCancellation.fromJSON(object.cancellation)
        : undefined,
    };
  },

  toJSON(message: CancelRequest): unknown {
    const obj: any = {};
    if (message.quoteId !== undefined) {
      obj.quote_id = message.quoteId;
    }
    if (message.cancellation !== undefined) {
      obj.cancellation = GaslessCancellation.toJSON(message.cancellation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelRequest>, I>>(
    base?: I,
  ): CancelRequest {
    return CancelRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelRequest>, I>>(
    object: I,
  ): CancelRequest {
    const message = createBaseCancelRequest();
    message.quoteId = object.quoteId ?? "";
    message.cancellation =
      object.cancellation !== undefined && object.cancellation !== null
        ? GaslessCancellation.fromPartial(object.cancellation)
        : undefined;
    return message;
  },
};

function createBaseCancelResponse(): CancelResponse {
  return { status: "" };
}

export const CancelResponse: MessageFns<CancelResponse> = {
  fromJSON(object: any): CancelResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: CancelResponse): unknown {
    const obj: any = {};
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelResponse>, I>>(
    base?: I,
  ): CancelResponse {
    return CancelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelResponse>, I>>(
    object: I,
  ): CancelResponse {
    const message = createBaseCancelResponse();
    message.status = object.status ?? "";
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
